////
Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
////
= Javadoc API Documentation

The table below contains links to the Javadoc API Documentation for the components you are most likely to use directly in code.

|===
| Component | Description

| link:javadoc/log4j-api/index.html[API]
| The logging interface (i.e., Log4j API) that applications should use and code against.

| link:javadoc/log4j-core/index.html[Implementation]
| The logging implementation (i.e., Log4j Core) that contains appenders, layouts, filters, and more.

| link:javadoc/log4j-jakarta-web/index.html[Log4j Web]
| Tools to use Log4j Core in Jakarta EE applications.

| link:javadoc/log4j-jpa/index.html[Log4j JPA]
| Tools to use Log4j Core with the Java Persistence API.
|===
