////
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
////
= Javadoc API Documentation

The table below contains links to the Javadoc API Documentation for the components you are most likely to use directly in code.

|===
|Component |Description

|{log4j2-url}/javadoc/log4j-api[Log4j 2 API]
|The interface that applications should use and code against.

|link:javadoc/log4j-kit/index.html[Implementation helper kit]
|Common helper functions for Log4j API implementations.

|link:javadoc/log4j-plugins/index.html[Dependency injection kit]
|Dependency injection artifact used in Log4j 3 Core.

|link:javadoc/log4j-core/index.html[Reference implementation]
|The standard implementation, also called the Log4j 3 Core, that contains Appenders, Filters, and more.

|link:javadoc/log4j-async-logger/index.html[Asynchronous logger]
|An alternative asynchronous logger implementation for Log4j 3 Core, based on LMAX Disruptor.
|===
