////
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
////
= Log4j 2 API
Ralph Goers <rgoers@apache.org>;

== Scoped Context
The link:../log4j-api/apidocs/org/apache/logging/log4j/ScopedContext.html[`ScopedContext`]
is available in Log4j API releases 2.24.0 and greater.

The `ScopedContext` is similar to the ThreadContextMap in that it allows key/value pairs to be included
in many log events. However, the pairs in a `ScopedContext` are only available to
application code and log events running within the scope of the `ScopeContext` object.

The `ScopeContext` is essentially a builder that allows key/value pairs to be added to it
prior to invoking a method. The key/value pairs are available to any code running within
that method and will be included in all logging events as if they were part of the `ThreadContextMap`.

[source,java]
----
ScopedContext.newInstance()
    .where("id", UUID.randomUUID())
    .where("ipAddress", request.getRemoteAddr())
    .where("loginId", session.getAttribute("loginId"))
    .where("hostName", request.getServerName())
    .run(new Worker());

private class Worker implements Runnable {
    private static final Logger LOGGER = LogManager.getLogger(Worker.class);

    public void run() {
        LOGGER.debug("Performing work");
        String loginId = ScopedContext.get("loginId");
    }
}

----

The values in the ScopedContext can be any Java object. However, objects stored in the
context Map will be converted to Strings when stored in a LogEvent. To aid in
this Objects may implement the Renderable interface which provides a `render` method
to format the object. By default, objects will have their toString() method called
if they do not implement the Renderable interface.

Note that in the example above `UUID.randomUUID()` returns a UUID. By default, when it is
included in LogEvents its toString() method will be used.

=== Nested ScopedContexts

ScopedContexts may be nested. When creating a nested context the default behavior is to
hide the key/value pairs of the parent context. The may be included by passing `true` to
the newInstance method when creating the child context.


[source,java]
----
        ScopedContext.newInstance().where("key1", "value1").run(() -> {
            assertThat(ScopedContext.get("key1"), equalTo("value1"));
            ScopedContext.newInstance(true).where("key2", "value2").run(() -> {
                assertThat(ScopedContext.get("key1"), equalTo("value1"));
                assertThat(ScopedContext.get("key2"), equalTo("value2"));
            });
            ScopedContext.newInstance().where("key2", "value2").run(() -> {
                assertThat(ScopedContext.get("key1"), nullValue());
                assertThat(ScopedContext.get("key2"), equalTo("value2"));
            });
        });

----