staging:
  profile: ~
  whoami: 2.x-site-stg-out
  subdir: content/log4j/2.x


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 10580
# - Commit ID: fce6ce9bd4a8ecb7a70229e0d6182e296b9b86b7
# - Timestamp: 2025-01-27T12:37:47Z
