staging:
  profile: ~
  whoami: 2.x-site-stg-out
  subdir: content/log4j/2.x


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 12643
# - Commit ID: 78d4cb8ed3e7b59d4c6cabcf6b32c9f4781543bb
# - Timestamp: 2025-05-25T13:54:30Z
