staging:
  profile: ~
  whoami: 2.x-site-stg-out
  subdir: content/log4j/2.x


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 29121
# - Commit ID: e08c7ba214080f42b4c4fdbecd7cd8f5dfb34497
# - Timestamp: 2025-06-28T07:20:26Z
