staging:
  profile: ~
  whoami: 2.x-site-stg-out
  subdir: content/log4j/2.x


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 32048
# - Commit ID: 8398f5d8b92c36427ba1feab08b94a51c2bdb45b
# - Timestamp: 2025-06-13T14:26:09Z
