staging:
  profile: ~
  whoami: 2.x-site-stg-out
  subdir: content/log4j/2.x


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 25305
# - Commit ID: 75d7cf9a7abda3c9b01d34307d78c85aad6707de
# - Timestamp: 2026-05-10T10:21:34Z
