staging:
  profile: ~
  whoami: release/2.25.2-site-stg-out
  subdir: content/log4j/2.25.2


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 25916
# - Commit ID: 380b9f279dbfdafd4483f3b2f82847cfb09e95e8
# - Timestamp: 2025-09-18T18:14:15Z
