staging:
  profile: ~
  whoami: 2.x-site-stg-out
  subdir: content/log4j/2.x


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 11012
# - Commit ID: 58bd98ee3575fea02ebec8cfa9c2da60b7dd0ec8
# - Timestamp: 2025-05-19T08:32:12Z
