# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# .asf.yaml documentation:
# https://cwiki.apache.org/confluence/display/INFRA/Git+-+.asf.yaml+features
notifications:
  commits: commits@logging.apache.org
  # issues and PRs send their own emails to devs
  issues: notifications@logging.apache.org
  pullrequests: notifications@logging.apache.org
  jira_options: link label
github:
  description: "Apache Log4j 2 is an upgrade to Log4j that provides significant improvements over its predecessor, Log4j 1.x, and provides many of the improvements available in Logback while fixing some inherent problems in Logback's architecture."
  homepage: https://logging.apache.org/log4j/2.x/
  # enable GitHub Issues and Projects
  features:
    issues: true
    projects: true
  del_branch_on_merge: true
  # and enable support for our old Jira instance
  autolink_jira:
    - LOG4J2
  labels:
    - apache
    - api
    - java
    - jvm
    - library
    - log4j
    - log4j2
    - logging
    - logger
    - api
    - async
    - asynchronous
    - syslog
    - structured-logging
    - json
    - performance
    - high-performance
    #  ultra-high-max-plus-performance
    - concurrency
  protected_branches:
    # Prevent force pushes to primary branches
    master: {}
    release-2.x: {}
