staging:
  profile: ~
  whoami: 2.x-site-stg-out
  subdir: content/log4j/2.x


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 26215
# - Commit ID: d54bf0a12672495e68e3498cc4268ad807df62f8
# - Timestamp: 2025-10-29T07:30:57Z
