publish:
  profile: ~
  whoami: main-site-pro-out
  subdir: content/log4j/3.x


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 20304
# - Commit ID: d12724d13676cb058e5d261b613ddd9cc80332c2
# - Timestamp: 2025-03-21T08:26:36Z
