publish:
  whoami: 2.x-site-pro-out
  subdir: content/log4j/2.x


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 15951
# - Commit ID: 7c9a7ed402934b9cc950526d0fe1fbf43d5381fc
# - Timestamp: 2025-06-18T07:06:35Z
