staging:
  profile: ~
  whoami: main-site-stg-out
  subdir: content/log4j/3.x


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 25936
# - Commit ID: 608b718729375a594914bbceb293ae5bf5432841
# - Timestamp: 2025-03-17T11:55:08Z
