staging:
  profile: ~
  whoami: main-site-stg-out
  subdir: content/log4j/3.x


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 15916
# - Commit ID: fec2473188badaac5cf2904a3a2d76fa5e8d2691
# - Timestamp: 2025-06-13T14:19:42Z
