staging:
  profile: ~
  whoami: 2.x-site-stg-out
  subdir: content/log4j/2.x


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 24344
# - Commit ID: e2cdf23953514a4caa8b95ebf390f55a4f9e34d8
# - Timestamp: 2025-03-21T08:28:25Z
