staging:
  profile: ~
  whoami: 2.x-site-stg-out
  subdir: content/log4j/2.x


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 26504
# - Commit ID: 296d1d7c3d8d79771c1aa84f2a22dd0bdb18b0c3
# - Timestamp: 2025-11-10T09:48:17Z
