////
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

         https://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
////

:log4j-changelog-uri: https://github.com/apache/logging-log4j-tools/tree/master/log4j-changelog
:log4j-changelog-ref: {log4j-changelog-uri}[log4j-changelog]

== Where are changelogs stored?

Changelogs are stored in xref:src/changelog[`src/changelog`] directory.

{log4j-changelog-ref} is used to generate AsciiDoc-formatted release notes during Maven `pre-site` phase and export them to xref:target/generated-sources/site/asciidoc/changelog[`target/generated-sources/site/asciidoc/changelog`] directory.
These exported AsciiDoc files are not committed, since they are only relevant for the website, and they cause merge-conflicts between feature branches.
`./mvnw site` command can be used to manually generate these files.

See {log4j-changelog-ref} project for further details; how to use this changelog system, what steps are needed while making a new release, etc.

== How can I create a changelog entry?

For the impatient, simply copy one of the existing `<issueId>_<summary>.xml` files in xref:src/changelog/.2.x.x[`src/changelog/.2.x.x`] directory and adapt to your needs.
See {log4j-changelog-uri}/README.adoc#changelog-entry-file[the official documentation] for details.
