////
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
////

:jboss-logging-link: https://github.com/jboss-logging/jboss-logging[JBoss Logging]
:jcl-link: https://commons.apache.org/proper/commons-logging/[JCL (Apache Commons Logging)]
:jpl-link: https://openjdk.org/jeps/264[JPL (Java Platform Logging)]
:jul-link: https://docs.oracle.com/en/java/javase/{java-target-version}/core/java-logging-overview.html[JUL (Java Logging)]
:logback-link: https://logback.qos.ch/[Logback]
:slf4j-link: https://www.slf4j.org/[SLF4J]

= Log4j API

Log4j is essentially composed of a logging API called *Log4j API*, and its reference implementation called *Log4j Core*.

.What is a logging API and a logging implementation?
[%collapsible]
====
Logging APIs::
A logging API is an interface your code or your dependencies directly logs against.
It is implementation agnostic.
Log4j API, {slf4j-link}, {jul-link}, {jcl-link}, {jpl-link} and {jboss-logging-link} are major logging APIs.

Logging implementation::
A logging implementation is only required at runtime and can be changed without the need to recompile your software.
Log4j Core, {jul-link}, {logback-link} are the most well-known logging implementations.
====

[TIP]
====
Are you looking for a crash course on how to use Log4j in your application or library?
See xref:5min.adoc[].
You can also check out xref:manual/installation.adoc[] for the complete installation instructions.
====

Starting with version `2.24.4`, Log4j API is embraced as the target logging API for both Log4j 2 and Log4j 3.
Hence, **Log4j 3 does not contain a Log4j API module**, but instead implements _"the"_ Log4j API developed in Log4j 2 branch.
This ensures Log4j 2 users can safely migrate to Log4j 3 without any Log4j API compatibility concerns.

{log4j2-url}/manual/api.html[Read more on Log4j API in the Log4j 2 website...]
