////
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
////
[id=configuration]
= Configuration

Even moderately sized applications can contain thousands of logging statements.
To decide which of these statements will be logged and where, users need to configure Log4j Core in one of following ways:

* Through a xref:manual/configuration.adoc[configuration file]
* Through xref:manual/customconfig.adoc[programmatic configuration]

Some meta-configuration options (e.g., the configuration file location) are only available through xref:manual/systemproperties.adoc[system properties].
