////
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
////
[id=configuration]
= Configuration

Logging is a standard method for monitoring the health of an application and diagnosing problems that may arise within it.
Even moderately sized applications can contain thousands of logging statements.

To decide which of these statements will be logged and where, users need to configure Log4j Core in one of two ways:

* through a xref:manual/configuration.adoc[].
Since version 2.0, the configuration file format has been considered part of the public API and has remained stable across significant version upgrades.

* through xref:manual/customconfig.adoc[Programmatic Configuration], which provides a larger spectrum of possible customizations but might require code changes during version upgrades.

[NOTE]
====
To prevent a chicken-and-egg problem, users can only supply some configuration options (e.g., the configuration file location) through xref:manual/systemproperties.adoc[configuration properties].
====