////
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
////
= Configuration

Since logging is a common way to monitor the health of an application and diagnose problems that occur in it, even moderately sized applications can contain thousands of logging statements.

In order to decide which of these statements will be logged and where, users need to configure Log4j Core.

Log4j Core can be configured in two ways:

* through a <<log4j-core-configuration-file>>.
Since version 2.0 the configuration file format is considered as part of the public API, and it remains stable even across major version upgrades.

* through <<log4j-core-programmatic-configuration>>, which provides a larger spectrum of possible customizations, but might require code changes even for minor version upgrades, according to https://semver.org/[semantic versioning] rules.

[NOTE]
====
To prevent a chicken-and-egg problem some configuration options, such as the location of the configuration file can be supplied only through <<system-properties>>.
====

[#log4j-core-configuration-file]
== Configuration file

TIP: For a quick example of configuration file see the xref:manual/installation.adoc#impl-core-config[Configuring Log4j Core section].

Log4j Core can be configured using multiple configuration file formats.
Configuration factories for the XML, JSON, YAML and Java properties format are included in the `log4j-core` artifact.

Some configuration formats require additional dependencies to be present on the classpath, according to the table below.

include::partial$configuration-file-format-deps.adoc[]

[WARNING]
====
The format of the configuration file changed between Log4j{nbsp}1 and Log4j{nbsp}2.
Files in the Log4j{nbsp}1 formats are ignored by default.

To enable partial support for old configuration formats see xref:manual/migration.adoc#enabling-the-log4j-1-x-bridge[Enabling the Log4j{nbsp}1 bridge].
====

[id=automatic-configuration]
=== Configuration file location

Upon initialization of a new logger context, Log4j assigns it a context name and scans the following **classpath** locations for a configuration file:

. Files named `log4j2-test<contextName>.<extension>`
. Files named `log4j2-test.<extension>`,
. Files named `log4j2<contextName>.<extension>`
. Files named `log4j2.<extension>`,
. If no configuration file could be located a link:../javadoc/log4j-core/org/apache/logging/log4j/core/config/DefaultConfiguration[DefaultConfiguration] is used and a warning is printed by the status logger.
The default configuration prints all messages less specific than <<log4j2.level>> to the console.

The `<contextName>` and `<extension>` placeholders above have the following meaning

<contextName>:: depends on the runtime environment in which Log4j runs:

* for standalone Java SE application it is a random identifier,
* for web applications it is derived from the application descriptor.
See xref:manual/webapp.adoc#configuration[Log4j
 Web application configuration] for more details.

<extension>:: must be one of the file extensions assigned to a configuration file format:
+
[cols="1,1"]
|===
| Configuration file format | Extension

| XML
| `xml`

| JSON
| `json` or `jsn`

| YAML
| `yaml` or `yml`

|Java properties
| `properties`
|===

[NOTE]
====
It is also possible to override the location of the configuration file using the <<log4j2.configurationFile>>
configuration property.

In this case Log4j will guess the configuration file format from the extension of the provided configuration file or will use the default configuration factory if the extension is unknown.
See <<log4j2.configurationFactory>> for details.
====

=== Syntax

All configuration files are parsed into a tree of link:../javadoc/log4j-core/org/apache/logging/log4j/core/config/Node[Node]s, each representing a different Log4j component.
The root of the tree creates a link:../javadoc/log4j-core/org/apache/logging/log4j/core/config/Configuration[Configuration] object.

A node is a fairly simple structure that represents a single Log4j plugin (cf. xref:plugin-reference.adoc[] for a complete list) such as an appender, layout or logger configuration.
Each node has:

* a set of simple string key value pairs called **attributes**.
Attributes are **matched by name** against the list of available configuration options of a Log4j plugin.

* one distinguished attribute called **plugin type** specifies the kind of Log4j plugin we want to instantiate.

* a set of child nodes called **nested elements**.
They are **matched by type** against the list of nested components that a Log4j plugin accepts.

Log4j maps the concepts above to the specifics of the configuration format as follows:

[tabs]
=====
XML::
+
Since XML was the original configuration format developed, the mapping from configuration nodes and XML elements is trivial:
+
[id=configuration-with-xml]
====
* Each configuration node is represented by an XML element.
* Each configuration attribute is represented by an XML attribute.
* The **plugin type** of a node is equal to the name of the XML tag.
* Each configuration nested element is represented by a nested XML element.
====
+
[NOTE]
====
There is an alternative XML configuration format called "XML strict format" that is activated by setting the `strict` attribute of the main `<Configuration>` element to `true`.

It allows users to use arbitrary tag names as long as they provide the plugin type using a `type` property.
It was conceived as a simplified XML format that can be validated by an XML schema.

Nowadays, the automatically generated schemas published at https://logging.apache.org/xml/ns/ offer a better alternative and allow users to use the more concise syntax.
====

JSON::
+
In the JSON configuration format:
+
[id=configuration-with-json]
====
* Each configuration node is represented by a JSON object,
* JSON properties of type string, number or boolean are mapped to node attributes.
* JSON properties of type object or array are used to represent nested configuration elements.
* The **plugin type** of a JSON object is given by:
** the value of the `type` key, if present,
** or the key associated with the JSON object otherwise,
** if the JSON object representing the node is part of an array, the key associated to the JSON array is used.
====
+
[TIP]
====
If you need to specify multiple plugins of the same type, you can use JSON arrays.
The snippet below represents two plugins of type `File`.

[source,json]
----
{
  "File": [
    {
      "name": "file1"
    },
    {
      "name": "file2"
    }
  ]
}
----
====

YAML::
+
In the YAML configuration format:
+
[id=configuration-with-yaml]
====
* Each configuration node is represented by a YAML mapping,
* YAML properties of scalar type are mapped to node attributes.
* YAML properties of collection type are used to represent nested configuration elements.
* The **plugin type** of a YAML mapping is given by:
** the value of the `type` key, if present,
** or the key associated with the YAML mapping otherwise,
** if the YAML mapping representing the node is part of a YAML block sequence, the key associated to the YAML sequence is used.
====
+
[TIP]
====
If you need to specify multiple plugins of the same type, you can use YAML block sequences.
The snippet below represents two plugins of type `File`.

[source,yaml]
----
File:
  - name: file1
  - name: file2
----
====

Java properties::
+
The Java properties format is not well suited to represent hierarchical structures.
In the Java properties configuration format:
+
[id=configuration-with-properties]
====
* Properties that share a common prefix (e.g. `appender.foo`) are mapped to a subtree of the configuration node tree.
* Configuration attributes are specified by appending the name of the property (e.g. `name`) to the prefix of the node, separated by a dot (e.g. `appender.foo.name`).
* The **plugin type** must necessarily be specified as an attribute named `type`.
* Nested elements are created by:
** choosing an arbitrary id for the nested component (e.g. `<0>`),
** appending the id to the prefix of the parent component (e.g. `appender.foo.<0>`),
** specifying the type of the nested plugin by assigning a `type` attribute (e.g. `appender.foo.<0>.type`).
====
+
[NOTE]
====
The id assigned to nested components is only used for sorting purposes.
However, some components assign a special meaning to some ids.
See a list of exceptions below:
====
+
.Properties format quirks
[%collapsible,#properties-format-quirks]
====
The Java properties configuration format is by far the most verbose of the available formats.
In order to make it more usable a series of exceptions to the rules in <<configuration-with-properties,Java properties syntax>> have been introduced over time:

. The following direct children of `Configuration` have predefined prefixes and do not require to specify a `type`
attribute:
* The xref:plugin-reference.adoc#org-apache-logging-log4j_log4j-core_org-apache-logging-log4j-core-config-AppendersPlugin[Appender container] has a predefined `appender` prefix.
* The xref:plugin-reference.adoc##org-apache-logging-log4j_log4j-core_org-apache-logging-log4j-core-config-CustomLevels[Custom levels container] has a predefined `customLevel` prefix.
* The xref:plugin-reference.adoc#org-apache-logging-log4j_log4j-core_org-apache-logging-log4j-core-config-LoggersPlugin[Loggers container] has a predefined `logger` prefix.
* The xref:plugin-reference.adoc#org-apache-logging-log4j_log4j-core_org-apache-logging-log4j-core-config-PropertiesPlugin[Properties container] has a predefined `property` prefix.
* The xref:plugin-reference.adoc#org-apache-logging-log4j_log4j-core_org-apache-logging-log4j-core-config-ScriptsPlugin[Scripts container] has a predefined `script` prefix.
. Properties that start with `property` are used for <<property-substitution>>.
Their syntax is `property.<key> = <value>`.
. The root logger can be configured using properties that start with `rootLogger`.
. A shorthand notation is available that allows users to write:
+
----
rootLogger = INFO, APPENDER
----
+
instead of:
+
----
rootLogger.level = INFO
rootLogger.appenderRef.0.ref = APPENDER
----
. All the keys of the form `logger.<name>.appenderRef.<id>`, where `<name>` and `<id>` are arbitrary, are considered appender references.
====
=====

=== Main configuration elements

Log4j Core's logging pipeline is quite complex (see xref:manual/architecture.adoc[Architecture]), but most users only require these elements:

Loggers::
+
Loggers are the entry point of the logging pipeline, directly used in code.
Their configuration must specify which level of messages they log and to which appenders they send the messages.

Appenders::
+
Appenders are the exit point of the logging pipeline.
They decide to which resource (console, file, database, etc.) the log event is sent.
For a complete list see xref:manual/appenders.adoc[Appenders].
In this chapter we will only use the xref:manual/appenders.adoc#consoleappender[console appender] and the xref:manual/appenders.adoc#fileappender[file appender] in the examples.

Layouts::
+
Layouts tell appenders how they should format the log event: text, JSON, XML, etc.
For a complete list see xref:manual/layouts.adoc[Layouts].
In this chapter we will only use the xref:manual/layouts.adoc#pattern-layout[textual pattern layout] and xref:manual/json-template-layout.adoc[JSON template layout] in the examples.

A moderately complex configuration might look like this:

[tabs]
====
XML::
+
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<Configuration xmlns="https://logging.apache.org/xml/ns">
  <Appenders>
    <Console name="CONSOLE" target="SYSTEM_OUT">
      <PatternLayout pattern="%p - %m%n"/>
    </Console>
    <File name="AUDIT" fileName="logs/audit.log">
      <JsonTemplateLayout/>
    </File>
    <File name="MAIN" fileName="logs/main.log">
      <PatternLayout pattern="%d [%t] %p %c - %m%n"/>
    </File>
  </Appenders>
  <Loggers>
    <Root level="WARN">
      <AppenderRef ref="CONSOLE"/>
      <AppenderRef ref="MAIN"/>
    </Root>
    <Logger name="org.example.audit" level="INFO">
      <AppenderRef ref="AUDIT"/>
    </Logger>
  </Loggers>
</Configuration>
----

JSON::
+
[source,json]
----
{
  "Configuration": {
    "Appenders": {
      "Console": {
        "name": "CONSOLE",
        "target": "SYSTEM_OUT",
        "PatternLayout": {
          "pattern": "%p - %m%n"
        }
      },
      "File": [
        {
          "name": "AUDIT",
          "fileName": "logs/audit.log",
          "JsonTemplateLayout": {}
        },
        {
          "name": "MAIN",
          "fileName": "logs/main.log",
          "PatternLayout": {
            "pattern": "%d [%t] %p %c - %m%n"
          }
        }
      ]
    },
    "Loggers": {
      "Root": {
        "level": "WARN",
        "AppenderRef": [
          {
            "ref": "CONSOLE"
          },
          {
            "ref": "MAIN"
          }
        ]
      },
      "Logger": {
        "name": "org.example.audit",
        "level": "INFO",
        "AppenderRef": {
          "ref": "AUDIT"
        }
      }
    }
  }
}
----

YAML::
+
[source,yaml]
----
Configuration:
  Appenders:
    Console:
      - name: "CONSOLE"
        target: "SYSTEM_OUT"
        PatternLayout:
          pattern: "%p - %m%n"
    File:
      - name: "AUDIT"
        fileName: "logs/audit.log"
        JsonTemplateLayout: { }
      - name: "MAIN"
        fileName: "logs/main.log"
        PatternLayout:
          pattern: "%d [%t] %p %c - %m%n"
  Loggers:
    Root:
      level: "WARN"
      AppenderRef:
        - ref: "CONSOLE"
        - ref: "MAIN"
      Logger:
        name: "org.example.audit"
        level: "INFO"
        AppenderRef:
          ref: "AUDIT"
----

Java properties::
+
[source,properties]
----
appender.0.type = Console
appender.0.name = CONSOLE
appender.0.target = SYSTEM_OUT
appender.0.layout.type = PatternLayout
appender.0.layout.pattern = %p - %m%n

appender.1.type = File
appender.1.name = AUDIT
appender.1.fileName = logs/audit.log
appender.1.layout.type = JsonTemplateLayout

appender.2.type = File
appender.2.name = MAIN
appender.2.fileName = logs/main.log
appender.2.layout.type = PatternLayout
appender.2.layout.pattern = %d [%t] %p %c - %m%n

rootLogger.level = WARN
rootLogger.appenderRef.0.ref = CONSOLE
rootLogger.appenderRef.1.ref = MAIN

logger.0.name = org.example.audit
logger.0.level = INFO
logger.0.appenderRef.0.ref = AUDIT
----
====

[id=property-substitution]
=== Property substitution

[#log4j-core-programmatic-configuration]
== Programmatic configuration

include::_properties.adoc[leveloffset=+1]