////
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
////

= Levels

Log levels are used to categorize log events by severity and control the verbosity of the logs.
They are one of many xref:manual/api.adoc#fish-tagging[_fish tagging_ capabilities provided by Log4j API].
Using levels, you can filter out less important logs and focus on the most critical ones.

Log4j contains following predefined levels:

[%header,cols="1m,1"]
|===
|Name |Priority
|OFF |0
|FATAL |100
|ERROR |200
|WARN |300
|INFO |400
|DEBUG |500
|TRACE |600
|ALL |`Integer.MAX_VALUE`
|===

A level is composed of a case-sensitive name and a *priority* (of type `int`), which is used to define an order while comparing two.
Priority can be used in several contexts to express a filtering capability, for instance:

* `WARN` is _less severe_ than `ERROR`
* `WARN` is _more specific_ than `ERROR`

The entry point to log levels are through link:../javadoc/log4j-api/org/apache/logging/log4j/Level.html[`Level`].
Predefined levels are available for Log4j API integrators through link:../javadoc/log4j-api/org/apache/logging/log4j/spi/StandardLevel.html[`StandardLevel`].

[NOTE]
====
The `OFF` and `ALL` levels are not intended to be used on calls to the logging API.
Specifying `OFF` in the configuration implies no logging events should match, while specifying `ALL` means all events match, including custom events.
`OFF` can be used on logging API calls in special cases where the event should always be logged regardless of the configuration.
However, it is generally recommended that a xref:manual/markers.adoc[marker] with a corresponding global xref:manual/filters.adoc#MarkerFilter[marker filter] be used instead.
====

[#usage]
== [[StandardLoggerInterface]] Usage

You can specify the log level while using `Logger` in several ways:

[source,java]
----
LOGGER.info("Hello, {}!", userName); // <1>
LOGGER.log(Level.INFO, "Hello, {}!", userName); // <2>
----
<1> Using `Logger#info()` to log a message at `INFO` level
<2> Using `Logger#log()` to log a message and specifying the `INFO` level explicitly

[#DefiningLevelsInCode]
=== Custom log levels

Users can programmatically define custom levels using link:../javadoc/log4j-api/org/apache/logging/log4j/Level.html#forName(java.lang.String,int)[the `Level.forName()` method]:

[source,java]
----
public final class CustomLogLevel {

    public static final Level VERBOSE = Level.forName("VERBOSE", 550); // <1>

}
----
<1> Creating a custom level with name `VERBOSE` and priority 550

Once defined, you can log messages at this level by calling the `Logger#log()` method and passing the custom log level:

[source,java]
----
public class PurchaseOrder {

    private static final Logger LOGGER = LogManager.getLogger();

    public PurchaseOrder(String id) {
        LOGGER.log(CustomLogLevel.VERBOSE, "Creating purchase order with ID `{}`", id); // <1>
        // ...
    }

    // ...

}
----
<1> Logging with the created custom level

[#config]
== Configuration

Levels can be used in various ways in a configuration file.
We will explain some important ones from multiple logging implementations.

[#config-core]
=== Log4j Core

Log4j Core, the reference implementation of Log4j API, has extensive support for levels.
It allows both <<config-core-filter,basic level-based filtering>> and <<DefiningLevelsInConfiguration,custom log levels>>.

[#config-core-filter]
==== Basic filtering

Filtering on levels for loggers is a pretty common example:

[tabs]
====
XML::
+
.Snippet from an example {antora-examples-url}/manual/customloglevels/filtering/log4j2.xml[`log4j2.xml`] configuring level-filtered loggers
[source,xml]
----
include::example$manual/customloglevels/filtering/log4j2.xml[lines=14..19,indent=0]
----

JSON::
+
.Snippet from an example {antora-examples-url}/manual/customloglevels/filtering/log4j2.json[`log4j2.json`] configuring level-filtered loggers
[source,xml]
----
include::example$manual/customloglevels/filtering/log4j2.json[lines=9..22,indent=0]
----

YAML::
+
.Snippet from an example {antora-examples-url}/manual/customloglevels/filtering/log4j2.yaml[`log4j2.yaml`] configuring level-filtered loggers
[source,xml]
----
include::example$manual/customloglevels/filtering/log4j2.yaml[lines=24..31,indent=0]
----

Properties::
+
.Snippet from an example {antora-examples-url}/manual/customloglevels/filtering/log4j2.properties[`log4j2.properties`] configuring level-filtered loggers
[source,xml]
----
include::example$manual/customloglevels/filtering/log4j2.properties[lines=21..24]
----
====
<1> Logs of level `INFO` or higher severity (i.e., `WARN`, `ERROR`, `FATAL`) are allowed for `com.mycompany` package
<2> Logs of level `ERROR` or higher severity (i.e., `FATAL`) are allowed for the rest

[#DefiningLevelsInConfiguration]
==== Custom log levels

Log4j Core, the reference implementation of Log4j API, requires a custom level to be defined first, before it can be used in a configuration file.
To facilitate this, the `CustomLevel` configuration element is used to define a custom level.
Internally it calls the same `Level.forName()` method discussed in <<DefiningLevelsInCode>>.

The following example shows a configuration that defines the `VERBOSE` custom log level and uses it to filter log events sent to the console.

[tabs]
====
XML::
+
.Snippet from an example {antora-examples-url}/manual/customloglevels/custom/log4j2.xml[`log4j2.xml`] configuring custom log levels
[source,xml]
----
include::example$manual/customloglevels/custom/log4j2.xml[lines=17..26,indent=0]
----

JSON::
+
.Snippet from an example {antora-examples-url}/manual/customloglevels/custom/log4j2.json[`log4j2.json`] configuring custom log levels
[source,xml]
----
include::example$manual/customloglevels/custom/log4j2.json[lines=13..32,indent=0]
----

YAML::
+
.Snippet from an example {antora-examples-url}/manual/customloglevels/custom/log4j2.yaml[`log4j2.yaml`] configuring custom log levels
[source,xml]
----
include::example$manual/customloglevels/custom/log4j2.yaml[lines=27..37,indent=0]
----

Properties::
+
.Snippet from an example {antora-examples-url}/manual/customloglevels/custom/log4j2.properties[`log4j2.properties`] configuring custom log levels
[source,xml]
----
include::example$manual/customloglevels/custom/log4j2.properties[lines=24..30]
----
====
<1> Defining the `VERBOSE` custom log level
<2> Only events of `VERBOSE` level or higher severity are sent to the console

[#config-logback]
=== Logback

{logback-url}[Logback] can be configured as follows to define level-filtered loggers:

.Snippet from an example {antora-examples-url}/manual/customloglevels/filtering/logback.xml[`logback.xml`] configuring level-filtered loggers
[source,xml]
----
include::example$manual/customloglevels/filtering/logback.xml[lines=29..32,indent=0]
----
