////
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
////
= Levels

Log levels are used to categorize log events by severity and control the verbosity of the logs.
They are one of many xref:manual/api.adoc#fish-tagging[_fish tagging_ capabilities provided by Log4j API].
Using levels, you can filter out less important logs and focus on the most critical ones.

Log4j contains following predefined levels:

[%header,cols="1m,1"]
|===
|Name |Priority
|OFF |0
|FATAL |100
|ERROR |200
|WARN |300
|INFO |400
|DEBUG |500
|TRACE |600
|ALL |`Integer.MAX_VALUE`
|===

A level is composed of a case-sensitive name and a *priority* (of type `int`), which is used to define an order while comparing two.
Priority can be used in several contexts to express a filtering capability, for instance:

* `WARN` is _less severe_ than `ERROR`
* `WARN` is _more specific_ than `ERROR`

The entry point to log levels are through link:../javadoc/log4j-api/org/apache/logging/log4j/Level.html[`Level`].
Predefined levels are available for Log4j API integrators through link:../javadoc/log4j-api/org/apache/logging/log4j/spi/StandardLevel.html[`StandardLevel`].

[#usage]
== [[StandardLoggerInterface]] Usage

You can specify the log level while using `Logger` in several ways:

[source,java]
----
LOGGER.info("Hello, {}!", userName); // <1>
LOGGER.log(Level.INFO, "Hello, {}!", userName); // <2>
----
<1> Using `Logger#info()` to log a message at `INFO` level
<2> Using `Logger#log()` to log a message and specifying the `INFO` level explicitly

There are several ways levels can be employed in the Log4j configuration file for filtering purposes.
Filtering on levels for loggers is a pretty common example:
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<Configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xmlns="https://logging.apache.org/xml/ns"
               xsi:schemaLocation="
                       https://logging.apache.org/xml/ns
                       https://logging.apache.org/xml/ns/log4j-config-2.xsd">

  <appenders>
    <Console name="CONSOLE">
      <JsonTemplateLayout/>
    </Console>
  </appenders>

  <loggers>
    <logger name="com.mycompany" level="INFO"/><!--1-->
    <root level="ERROR"><!--2-->
      <AppenderRef ref="CONSOLE"/>
    </root>
  </loggers>

</Configuration>
----
<1> Logs of level `INFO` or higher severity (i.e., `WARN`, `ERROR`, `FATAL`) are allowed for `com.mycompany` package
<2> Logs of level `ERROR` or higher severity (i.e., `FATAL`) are allowed for the rest

[[top]]

[#DefiningLevelsInCode]
== Defining custom log levels programmatically

Users can programmatically define custom levels using link:../javadoc/log4j-api/org/apache/logging/log4j/Level.html#forName(java.lang.String,int)[the `Level.forName()` method]:

[source,java]
----
public final class CustomLogLevel {

    public static final Level VERBOSE = Level.forName("VERBOSE", 550); // <1>

}
----
<1> Creating a custom level with name `VERBOSE` and priority 550

Once defined, you can log messages at this level by calling the `Logger#log()` method and passing the custom log level:

[source,java]
----
public class PurchaseOrder {

    private static final Logger LOGGER = LogManager.getLogger();

    public PurchaseOrder(String id) {
        LOGGER.log(CustomLogLevel.VERBOSE, "Creating purchase order with ID `{}`", id); // <1>
        // ...
    }

    // ...

}
----
<1> Logging with the created custom level

[#DefiningLevelsInConfiguration]
== Defining custom log levels in configuration

Similar to defining log levels programmatically, a custom level must be defined first, before it can be used in a configuration file.
To facilitate this, the `CustomLevel` configuration element is used to define a custom level.
Internally it calls the same `Level.forName()` method discussed in <<DefiningLevelsInCode>>.

The following example shows a configuration that defines the `VERBOSE` custom log level and uses it to filter log events sent to the console.

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<Configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xmlns="https://logging.apache.org/xml/ns"
               xsi:schemaLocation="
                       https://logging.apache.org/xml/ns
                       https://logging.apache.org/xml/ns/log4j-config-2.xsd">

  <CustomLevels><!--1-->
    <CustomLevel name="VERBOSE" intLevel="550"/>
  </CustomLevels>

  <appenders>
    <Console name="CONSOLE">
      <PatternLayout/>
    </Console>
    <File name="FILE" fileName="logs/app.log">
      <PatternLayout/>
    </File>
  </appenders>

  <loggers>
    <root level="TRACE">
      <AppenderRef ref="CONSOLE" level="VERBOSE" /><!--2-->
      <AppenderRef ref="FILE"/>
    </root>
  </loggers>

</Configuration>
----
<1> Defining the `VERBOSE` custom log level
<2> Only events of `VERBOSE` level or higher severity are sent to the console
