////
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
////

= Extending

Log4j provides numerous extension points to adapt it for custom needs.
Several of such extension points are covered in the page of the associated component:

* Log4j API
** {log4j2-url}/manual/customloglevels.html[Extending levels]
** {log4j2-url}/manual/markers.html[Extending markers]
** {log4j2-url}/manual/messages.html#extending[Extending messages]
** {log4j2-url}/manual/thread-context.html#extending[Extending thread context]
* Log4j Core
** xref:manual/appenders.adoc#extending[Extending appenders]
** xref:manual/filters.adoc#extending[Extending filters]
** xref:manual/layouts.adoc#extending[Extending layouts]
*** xref:manual/json-template-layout.adoc#extending[Extending JSON Template Layout]
*** xref:manual/pattern-layout.adoc#extending[Extending Pattern Layout]
** xref:manual/lookups.adoc#extending[Extending lookups]

This section guides you on the rest of the Log4j extension points.

[#mechanisms]
== Extension mechanisms

Log4j allows extensions primarily using following mechanisms:

[#Custom_Plugins]
=== Plugins

include::partial$manual/plugin-preliminaries.adoc[]

[#bindings]
=== Bindings

The Log4j plugin system was enhanced in 3.0 to support arbitrary bindings for xref:manual/dependencyinjection.adoc[dependency injection].
Many shared components in Log4j could be configured via system properties or similar to include a fully qualified class name to use.
Using custom bindings, however, these custom classes can be configured as code.
Default bindings are configured in {project-github-url}/log4j-core/src/main/java/org/apache/logging/log4j/core/impl/CoreDefaultBundle.java[`CoreDefaultBundle`].
Custom bindings can be installed by defining a link:../javadoc/log4j-plugins/org/apache/logging/log4j/plugins/di/spi/ConfigurableInstanceFactoryPostProcessor.html[`ConfigurableInstanceFactoryPostProcessor`] service class which invokes `ConfigurableInstanceFactory::registerBundle` to register the bundle class containing the bindings.
This approach is more portable than the legacy approach of using system properties to define the classes as it removes ambiguity of `ClassLoader` ownership and other details of modules and similar runtimes.

[#service-loader]
=== ``ServiceLoader``s

https://docs.oracle.com/javase/{java-target-version}/docs/api/java/util/ServiceLoader.html[`ServiceLoader`] is a simple service-provider loading facility baked into the Java platform itself.
Log4j uses ``ServiceLoader``s for extending places where

* The service needs to be implementation agnostic.
As a result, <<Custom_Plugins,the Log4j plugin system>> cannot be used, since it is provided by the logging implementation, i.e., Log4j Core.
For instance, this is why {log4j2-url}/manual/thread-context.html#extending[extending Thread Context], which is a Log4j API component, works using ``ServiceLoader``s.

* The service needs to be loaded before <<Custom_Plugins,the Log4j plugin system>>.
For instance, this is why <<Provider,extending `Provider`>> works using ``ServiceLoader``s.

Refer to https://docs.oracle.com/javase/{java-target-version}/docs/api/java/util/ServiceLoader.html[the `ServiceLoader` documentation] for details.

[#system-properties]
=== System properties

Log4j uses system properties to determine the fully-qualified class name (FQCN) to load for extending a certain functionality.
For instance, <<MessageFactory, extending `MessageFactory2`>> works using system properties.

[WARNING]
====
Loading a class using _only_ its FQCN can result in unexpected behaviour when there are multiple class loaders.
====

[#points]
== Extension points

In this section we will guide you on certain Log4j extension points that are not covered elsewhere.

[#Provider]
=== `Provider`

link:../javadoc/log4j-api/org/apache/logging/log4j/spi/Provider.html[`Provider`] is the anchor contract binding Log4j API to an implementation.
For instance, it has been implemented by Log4j Core, Log4j-to-JUL bridge, and Log4j-to-SLF4J bridge modules.

Under the hood, link:../javadoc/log4j-api/org/apache/logging/log4j/LogManager.html[`LogManager`] locates a `Provider` implementation using <<service-loader,the `ServiceLoader` mechanism>>, and delegates invocations to it.
Hence, you can extend it by providing a `org.apache.logging.log4j.spi.Provider` implementation in the form of a `ServiceLoader`.

Having multiple ``Provider``s in the classpath is strongly discouraged.
A specific provider can be <<bindings,bound>> using a custom bundle class if Log4j Core is also available.
Alternatively, you can use xref:manual/systemproperties.adoc#log4j.provider[the `log4j.provider` property] to explicitly select one.

[#LoggerContextFactory]
=== `LoggerContextFactory`

link:../javadoc/log4j-api/org/apache/logging/log4j/spi/LoggerContextFactory.html[`LoggerContextFactory`] is the factory class used by Log4j API implementations to create xref:manual/architecture.adoc#LoggerContext[`LoggerContext`]s.
If you are using Log4j Core, you can use <<ContextSelector>>s to influence the way its `LoggerContextFactory` implementation works.
If you are creating a new Log4j API implementation, you should <<Provider,provide a custom `Provider`>> to introduce your custom `LoggerContextFactory` implementation.

[#ContextSelector]
=== `ContextSelector`

link:../javadoc/log4j-core/org/apache/logging/log4j/core/impl/Log4jContextFactory.html[`Log4jContextFactory`], the Log4j Core implementation of <<LoggerContextFactory>>, delegates the actual work to a link:../javadoc/log4j-core/org/apache/logging/log4j/core/selector/ContextSelector.html[`ContextSelector`].
This should be configured as a `ContextSelector` binding in a <<bindings,custom binding>>.
Alternatively, it can be configured using xref:manual/systemproperties.adoc#log4j.loggerContext.selector[the `log4j.loggerContext.selector` property].

[#ConfigurationFactory]
=== `ConfigurationFactory`

link:../javadoc/log4j-core/org/apache/logging/log4j/core/config/ConfigurationFactory.html[`ConfigurationFactory`] is the factory class used by Log4j Core to create link:../javadoc/log4j-core/org/apache/logging/log4j/core/config/Configuration.html[`Configuration`] instances given a xref:manual/architecture.adoc#LoggerContext[`LoggerContext`] and a link:../javadoc/log4j-core/org/apache/logging/log4j/core/config/ConfigurationSource.html[`ConfigurationSource`].

You can provide a custom `ConfigurationFactory` in the form of a <<Custom_Plugins,plugin>>.
For example, see {project-github-url}/log4j-core/src/main/java/org/apache/logging/log4j/core/config/xml/XmlConfigurationFactory.java[`XmlConfigurationFactory.java`] and {project-github-url}/log4j-core/src/main/java/org/apache/logging/log4j/core/config/xml/XmlConfiguration.java[`XmlConfiguration.java`] of Log4j Core.

A specific configuration factory can be bound in a <<bindings,custom bundle class>> which can take priority over the default configuration factories.
You can also use xref:manual/systemproperties.adoc#log4j.configuration.factory[the `log4j.configuration.factory` property] to explicitly set a `ConfigurationFactory` to be used before any other factory implementation.

[#LoggerConfig]
=== `LoggerConfig`

link:../javadoc/log4j-core/org/apache/logging/log4j/core/config/LoggerConfig.html[`LoggerConfig`] denotes the `Logger` configurations in a `Configuration`.
A custom `LoggerConfig` needs to satisfy the following conditions:

* It needs to extend from `LoggerConfig` class
* It needs to be declared as a <<Custom_Plugins,plugin>>
* It needs to include a `@Configurable` annotation on the class

For example, see `RootLogger` definition in {project-github-url}/log4j-core/src/main/java/org/apache/logging/log4j/core/config/LoggerConfig.java[`LoggerConfig.java`].

[#LogEventFactory]
=== `LogEventFactory`

Log4j Core uses link:../javadoc/log4j-core/org/apache/logging/log4j/core/impl/LogEventFactory.html[`LogEventFactory`] to create link:../javadoc/log4j-core/org/apache/logging/log4j/core/LogEvent.html[`LogEvent`]s.
You can replace the default `LogEventFactory` implementation with a custom one of yours by defining a <<bindings,custom binding>> for `LogEventFactory` or by using xref:manual/systemproperties.adoc#log4j.logEvent.factory[the `log4j.logEvent.factory` property].

[NOTE]
====
xref:manual/async.adoc[] discard `LogEventFactory` and any configuration related with it.
====

[#MessageFactory]
=== `MessageFactory2`

Log4j Core uses link:../javadoc/log4j-api/org/apache/logging/log4j/message/MessageFactory2.html[`MessageFactory2`] to create link:../javadoc/log4j-api/org/apache/logging/log4j/message/Message.html[`Message`]s.
You can replace the default `MessageFactory2` implementation with a custom one of yours by using xref:manual/systemproperties.adoc#log4j.message.factory[the `log4j.message.factory` property].

[IMPORTANT]
====
Message factory implementations are expected to interpret formatting patterns containing placeholders denoted with `{}`.
For instance, the default message factory chooses between a {log4j2-url}/manual/messages.html#SimpleMessage[`SimpleMessage`] and a {log4j2-url}/manual/messages.html#ParameterizedMessage[`ParameterizedMessage`] depending on the presence of placeholders in the formatting pattern.

If you want to change the placeholder style (e.g., switching from `{}` to `%s`), you should *not* replace the default message factory.
Because this will break the existing Log4j API calls using the standard placeholder style.
Instead, you can use link:../javadoc/log4j-api/org/apache/logging/log4j/LogManager.html[`LogManager`] methods accepting a message factory to create ``Logger``s with your custom message factory implementations.
====
