////
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
////
= Flow Tracing

Flow tracing in Log4j is an advanced logging technique designed to enhance 
the visibility of application processes. With this technique, developers can track 
data flow through their application using unique methods that log entry 
and exit points within the code.

These methods are:

* `traceEntry()` (Deprecated `entry()`)
* `traceExit()` (Deprecated: `exit()`)
* `throwing()`
* `catching()`

With these methods, we can investigate environments where traditional debugging is not possible, 
such as in production or during live application monitoring. 
Furthermore, new developers can be educated on the application's behavior by examining the logs.

Flow tracing offers a structured approach to all this.

== Flow Tracing Methods

The methods often used are `traceEntry()` and `traceExit()`.
As the name suggests, the "entry" method is used at the beginning and the "exit" method at the end of a method.

[source, java]
----
public void someMethod() {
    logger.traceEntry(); <1>
    // method body
    logger.traceExit(); <2>
}
----
<1> The `entry()` method is called at the beginning of the method.
<2> The `exit()` method is called at the end of the method.

Developers can call both `traceEntry()` and `traceExit()` methods with or without parameters.
In the case of `traceEntry()`, it makes sense to pass the method parameters on as arguments.

[source, java]
----
public void someMethod(String param) {
    logger.traceEntry(param); <1>
    // method body
    logger.traceExit(); <2>
}
----
<1> The `traceEntry()` method is called at the beginning of the method.
<2> The `traceExit()` method is called at the end of the method.

The `traceEntry()` also supports messages.

[source, java]
----
public void someMethod(String[] text) {
    logger.traceEntry(new JsonMessage(text)); <1>
    // method body
}
----
<1> Using the `JsonMessage` class to log the `text` parameter.

Very similar, it is possible to use `traceExit()` with methods that return a value.

[source, java]
----
public String someMethod() {
    String result = "Hello";
    // method body
    return logger.traceExit(result); <1>
}
----
<1> The `traceExit()` method can also return a value.

Developers can use the `catching()` and `throwing()` methods to work with exceptions.

The following code shows the `catching()` method. It will be called
inside the `catch` block of a try-catch statement.

The `catching()` method can be used by an application when it catches an
Exception that it will not rethrow, either explicitly or attached
to another Exception. The generated logging event will have an `ERROR` level.

[source, java]
----
public void someMethod() {
    try {
        // Let's assume an exception is thrown here
        String msg = messages[messages.length];        
    } catch (Exception ex) {
        logger.catching(ex); <1>
    }
}
----
<1> The `catching()` method logs exceptions that are caught and not rethrown.

The `throwing()` method is used to log exceptions that are thrown and not caught.
The code shows how to use the `throwing()` method- like `catching()`, which will be called
inside the `catch` block of a try-catch statement.

The `throwing()` method can be used by an application when it is throwing
an exception that is unlikely to be handled, such as a RuntimeException.
This will ensure that proper diagnostics are available if needed. 
The generated logging event will have an `ERROR` level.

[source, java]
----
public void someMethod() {
    try {
        // Let's assume an exception is thrown here
        String msg = messages[messages.length];        
    } catch (Exception ex) {
        logger.throwing(ex); <1>
    }
}
----
<1> The `throwing()` method logs exceptions that are thrown and not caught.

== Differences in flow tracing methods

Flow tracing methods have specific markers assigned and logs with a level of `TRACE`.
It's also noteworthy that all messages begin with "event".

The table below shows the methods and their unique features.

[cols="3,3,3", options="header"]
|===
| Method Name | Marker Name | Special Features

| `traceEntry()`
| `ENTER`, `FLOW`
| Can take a format string and a variable list of parameters.

| `entry()`
| `ENTER`, `FLOW`
| DEPRECATED. Accepts 0 to 4 parameters

| `traceExit()`
| `EXIT`, `FLOW`
| Handles return values differently based on the method signature.

| `exit()`
| `EXIT`, `FLOW`
| DEPRECATED.  Can be called with or without parameters.

| `throwing()`
| `THROWING`, `EXCEPTION`
| Typically used when an application throws an exception that is unlikely to be handled, such as a RuntimeException.

| `catching()`
| `CATCHING`, `EXCEPTION`
| Used when catching exceptions that are not rethrown; logs with ERROR level.

|===

== Flow Tracing Example Configuration

The following example demonstrates how to configure Log4j to use flow tracing.
Note: While developers should prefer the `JsonTemplateLayout` in production, this example uses `PatternLayout` for simplicity.

Two appenders are defined: `Console` and `File`.

The `Console` appender outputs logs to `SYSTEM_OUT`, typically the console. 
It includes a `ThresholdFilter` set to only accept messages at the `ERROR` level or above.
Less severe messages are filtered.

Similarly, the File appender directs logs to a file named `target/test.log`. 
The appenders configuration will create a new file for every application run.

Both appenders use the already mentioned `PatternLayout`, which includes detailed information such as time, log level, class name, line number, and method name.

Finally, in the Loggers section, the Root logger is set to a `TRACE` level, which is necessary to see flow tracing in action. 
The Root logger references the File appender, directing its output to the configured file.

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<Configuration>
  <Appenders>
    <Console name="Console" target="SYSTEM_OUT">
      <ThresholdFilter level="ERROR" onMatch="ACCEPT" onMismatch="DENY"/>
      <!-- Flow tracing is most useful with a pattern that shows location.
           Below pattern outputs class, line number and method name. -->
      <PatternLayout pattern="%d{HH:mm:ss.SSS} %-5level %class{36} %L %M - %msg%xEx%n"/>
    </Console>
    <File name="log" fileName="target/test.log" append="false">
      <PatternLayout pattern="%d{HH:mm:ss.SSS} %-5level %class{36} %L %M - %msg%xEx%n"/>
    </File>
  </Appenders>
  <Loggers>
    <Root level="trace">
      <AppenderRef ref="log"/>
    </Root>
  </Loggers>
</Configuration>
----

By changing the Root logger's level to `DEBUG`, developers can reduce the amount of output.
