////
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
////

= Reference implementation

The reference implementation of the xref:manual/api.adoc[] is called Log4j Core.
It is a versatile, reliable, feature-rich and production-ready implementation.
The remaining chapters of the manual describe the ins and outs of this logging implementation:

Do you want to learn about its architecture?::
Go to xref:manual/architecture.adoc[].

Do you want to install Log4j Core?::
Go to xref:manual/installation.adoc#impl-core[Installing Log4j Core].

Do you want to configure Log4j Core?::
Go to xref:manual/config-intro.adoc[].

Do you want to write custom components for Log4j Core?::
Go to xref:manual/extending.adoc[].

Do you want to tune your installation for a better performance?::
Go to xref:manual/performance.adoc[].