////
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
////

= Installation

Log4j features a separation between a logging API and its implementations:

* **The logging API** is directly used in your code or by your dependencies.
* **Logging implementations** are only required at runtime and can be changed without the need to recompile your software.

That is why the proper way to install Log4j depends on the kind of software you are writing:

* **Libraries** only require Log4j API and delegate the choice of the implementation to applications.
If a logging implementation is required by tests, it should be in the appropriate "test" scope.

* **Applications** need Log4j API for their own code, but also an implementation of each of the major Java logging APIs to support log statements from the libraries they use.

[#build-tool]
== Configuring the build tool

The easiest way to install Log4j is through a build tool such as Maven or Gradle.
The rest of the instructions in this page assume you use one of these.

[#bom]
=== Importing the Bill-of-Materials (aka. BOM)

To keep your Log4j module versions in sync with each other, a BOM (Bill of Material) file is provided for your convenience.
You need to import the BOM in your build tool of preference:

[tabs]
====
Maven::
+
[source,xml,subs="+attributes"]
----
<dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>org.apache.logging.log4j</groupId>
      <artifactId>log4j-bom</artifactId>
      <version>{log4j-core-version}</version>
      <scope>import</scope>
      <type>pom</type>
    </dependency>
  </dependencies>
</dependencyManagement>
----

Gradle::
+
[source,groovy,subs="+attributes"]
----
plugins {
  id 'io.spring.dependency-management' version '1.1.4' //<1>
}

dependencyManagement {
  imports {
    mavenBom 'org.apache.logging.log4j:log4j-bom:{log4j-core-version}'
  }
}
----
<1> The additional https://github.com/spring-gradle-plugins/dependency-management-plugin[Gradle plugin] required for dependency management functionality.
====

Once you import the BOM, you don't need to explicitly provide the versions of the Log4j artifacts managed by it.

[#api]
== Installing Log4j API

The easiest way to install Log4j API is through a dependency management tool such as Maven or Gradle, by adding the following dependency:

[tabs]
====
Maven::
+
[source,xml]
----
<dependency>
    <groupId>org.apache.logging.log4j</groupId>
    <artifactId>log4j-api</artifactId>
</dependency>
----

Gradle::
+
[source,groovy]
----
implementation 'org.apache.logging.log4j:log4j-api'
----
====

[#impl]
== Installing a logging implementation

The Log4j project maintains different implementations of the Log4j API:

`log4j-core`::
The reference implementation.
Refer to <<impl-core>> for the installation procedure.

`log4j-to-slf4j`::
The implementation that delegates logging to an SLF4J implementation.
Since currently only
https://logback.qos.ch/[Logback] implements SLF4J natively, refer to <<impl-logback>> for the installation procedure.

`log4j-to-jul`::
the  implementation that delegates logging to `java.util.logging`.
See <<impl-jul>> for the installation procedure.

Applications developers should also consider installing the appropriate bridges from the most commonly used logging APIs (Log4j API, SLF4J and `java.util.logging`) to the chosen implementation.

[IMPORTANT]
====
In order to ensure that your code does not directly depend on a particular logging implementation, the logging backend should be put in the appropriate scope of your dependency manager:

[cols="2,1m,1m"]
|===
.2+h| Software type
2+^h|Build tool

h| Maven
h| Gradle

| Application
| runtime
| runtimeOnly

| Library
| test
| testRuntimeOnly
|===
====

[#impl-core]
=== Installing Log4j Core

To install Log4j Core as logging implementation, you need to add the following dependencies to your application:

[tabs]
====
Maven::
+
[source,xml]
----
<dependencies>
    <dependency>
        <groupId>org.apache.logging.log4j</groupId>
        <artifactId>log4j-core</artifactId>
        <scope>runtime</scope>
    </dependency>
    <dependency>
        <groupId>org.apache.logging.log4j</groupId>
        <artifactId>log4j-jul</artifactId>
        <scope>runtime</scope>
    </dependency>
    <dependency>
        <groupId>org.apache.logging.log4j</groupId>
        <artifactId>log4j-slf4j2-impl</artifactId>
        <scope>runtime</scope>
    </dependency>
    ...
</dependencies>
----

Gradle::
+
[source,groovy]
----
runtimeOnly 'org.apache.logging.log4j:log4j-core'
runtimeOnly 'org.apache.logging.log4j:log4j-jul'
runtimeOnly 'org.apache.logging.log4j:log4j-slf4j2-impl'
----
====

In order to activate the bridge from JUL to Log4j API, you also need to add:

[source]
----
-Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager
----

to the JVM parameters in your application launcher.

[#impl-core-spring-boot]
==== Installing Log4j Core for Spring Boot applications

Spring Boot users should use the `spring-boot-starter-log4j2` starter and replace the dependencies above with:

[tabs]
====
Maven::
+
[source,xml]
----
<dependencies>
    <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter</artifactId>
        <scope>runtime</scope>
        <exclusions>
            <exclusion>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-logging</artifactId>
            </exclusion>
        </exclusions>
    </dependency>
    <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-log4j2</artifactId>
        <scope>runtime</scope>
    </dependency>
</dependencies>
----

Gradle::
+
[source,groovy]
----
configurations {
    all.exclude group: 'org.springframework.boot', module: 'spring-boot-starter-logging'
}

dependencies {
    runtimeOnly group: 'org.springframework.boot', module: 'spring-boot-starter-log4j2'
}
----

====

The activation of the bridge from JUL to Log4j API can be omitted, since it will be performed automatically by Spring Boot.

See also https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.logging[Spring Boot Logging documentation].

[#impl-core-config]
=== Configuring Log4j Core

As any other logging backend, Log4j Core needs to be properly configured.
Log4j supports many different configuration formats: JSON, XML, YAML, and Java properties.

To configure Log4j Core, see xref:manual/configuration.adoc[].
A basic configuration can be obtained by adding one of these files to your application's classpath:

[tabs]
====
log4j2.xml::
+
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<Configuration xmlns="https://logging.apache.org/xml/ns"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="https://logging.apache.org/xml/ns
                                   https://logging.apache.org/xml/ns/log4j-config-3.xsd">
  <appenders>
    <Console name="CONSOLE"/>
  </appenders>
  <loggers>
    <root level="INFO">
      <AppenderRef ref="Console"/>
    </root>
  </Loggers>
</Configuration>
----

log4j2.json::
+
[source,json]
----
{
  "Configuration": {
    "Appenders": {
      "Console": {
        "name": "CONSOLE"
      }
    },
    "Loggers": {
      "Root": {
        "level": "INFO",
        "AppenderRef": {
          "ref": "CONSOLE"
        }
      }
    }
  }
}
----

log4j2.yaml::
+
[source,yaml]
----
Configuration:
  Appenders:
    Console:
      name: CONSOLE
  Loggers:
    Root:
      level: INFO
      AppenderRef:
        ref: CONSOLE
----

log4j2.properties::
+
[source,properties]
----
Configuration.Appenders.Console.name = CONSOLE
Configuration.Loggers.Root.level = INFO
Configuration.Loggers.Root.AppenderRef.ref = CONSOLE
----
====

In order to use these formats, the following additional dependencies are required:

[tabs]
====
Maven::
+
[tabs]
=====

log4j2.xml::
+
JPMS users need to add:
+
[source,java]
----
module foo.bar {
    requires java.xml;
}
----
+
to their `module-info.java` descriptor.

log4j2.json::
+
No dependency required.

log4j2.yaml::
+
[source,xml]
----
<dependency>
    <groupId>org.apache.logging.log4j</groupId>
    <artifactId>log4j-config-yaml</artifactId>
</dependency>
----

log4j2.properties::
+
[source,xml]
----
<dependency>
    <groupId>org.apache.logging.log4j</groupId>
    <artifactId>log4j-config-properties</artifactId>
</dependency>
----

=====

Gradle::
+
[tabs]
=====

log4j2.xml::
+
JPMS users need to add:
+
[source,java]
----
module foo.bar {
    requires java.xml;
}
----
+
to their `module-info.java` descriptor.

log4j2.json::
+
No dependency required.

log4j2.yaml::
+
[source,groovy]
----
runtimeOnly 'org.apache.logging.log4j:log4j-config-yaml'
----

log4j2.properties::
+
[source,groovy]
----
runtimeOnly 'org.apache.logging.log4j:log4j-config-properties'
----

=====
====

[#impl-jul]
=== Installing JUL

Java SE contains a very simple logging implementation called `java.util.logging`.
Since it is embedded in the OpenJDK distribution, it only requires the addition of bridges from Log4j API and SLF4J:

[tabs]
====
Maven::
+
[source,xml,subs="+attributes"]
----
<dependencies>
    <dependency>
        <groupId>org.apache.logging.log4j</groupId>
        <artifactId>log4j-to-jul</artifactId>
        <scope>runtime</scope>
    </dependency>
    <dependency>
        <groupId>org.slf4j</groupId>
        <artifactId>slf4j-jdk14</artifactId>
        <version>{slf4j-version}</version>
        <scope>runtime</scope>
    </dependency>
    <!-- ... -->
</dependencies>
----

Gradle::
+
[source,groovy,subs="+attributes"]
----
runtimeOnly 'org.apache.logging.log4j:log4j-to-jul'
runtimeOnly 'org.slf4j:slf4j-jdk14:{slf4j-version}'
----
====

To configure JUL, see https://docs.oracle.com/en/java/javase/21/docs/api/java.logging/java/util/logging/LogManager.html[java.util.logging.LogManager].

[#impl-jul-spring-boot]
==== Installing JUL for Spring Boot applications

Spring Boot users also need to exclude the default `spring-boot-starter-logging` starter:

[tabs]
====
Maven::
+
[source,xml,subs="+attributes"]
----
<dependencies>
    <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter</artifactId>
        <scope>runtime</scope>
        <exclusions>
            <exclusion>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-logging</artifactId>
            </exclusion>
        </exclusions>
    </dependency>
</dependencies>
----

Gradle::
+
[source,groovy,subs="+attributes"]
----
configurations {
    all.exclude group: 'org.springframework.boot', module: 'spring-boot-starter-logging'
}
----

====

The activation of the bridge from JUL to Log4j API can be omitted, since it will be performed automatically by Spring Boot.

See also https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.logging[Spring Boot Logging documentation].

[#impl-logback]
=== Installing Logback

To install https://logback.qos.ch/[Logback] as the logging implementation, you need to add the following dependencies to your application:

[tabs]
====
Maven::
+
[source,xml]
----
<dependencies>
    <dependency>
        <groupId>org.apache.logging.log4j</groupId>
        <artifactId>log4j-jul</artifactId>
        <scope>runtime</scope>
    </dependency>
    <dependency>
        <groupId>org.apache.logging.log4j</groupId>
        <artifactId>log4j-to-slf4j</artifactId>
        <scope>runtime</scope>
    </dependency>
    <dependency>
        <groupId>ch.qos.logback</groupId>
        <artifactId>logback-classic</artifactId>
        <version>{logback-version}</version>
        <scope>runtime</scope>
    </dependency>
</dependencies>
----

Gradle::
+
[source,groovy,subs="+attributes"]
----
runtimeOnly 'org.apache.logging.log4j:log4j-jul'
runtimeOnly 'org.apache.logging.log4j:log4j-to-slf4j'
runtimeOnly 'ch.qos.logback:logback-classic:{logback-version}'
----
====

In order to activate the bridge from JUL to Log4j API, you also need to add:

[source]
----
-Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager
----

to your JVM parameters.

To configure Logback, see https://logback.qos.ch/manual/configuration.html[Logback's configuration documentation].
