////
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
////
= Markers

Markers allow to _tag_ log statements with a
link:../javadoc/log4j-api/org/apache/logging/log4j/Marker.html[`Marker`]
object, labeling them as belonging to a specific type.
For example, developers can use markers to tag log statements related to a particular subsystem or functionality.

By using markers, it is possible to filter log statements based on the `Marker`
and display only those log statements that are of interest, such as those
related to XML processing or SQL queries.

Markers offer more fine-grained control over log filtering beyond log levels or package names.

[#create]
== Creating Markers

[#simple-markers]
=== Simple markers

To create a `Marker`, create a field in your class using the `MarkerManager.getMarker()` method:

[source, java, indent=0]
----
include::example$manual/markers/MarkerExample.java[tag=create-marker]
----

Since a `Marker` is reusable across multiple log statements, storing it in a `static final` field makes it a constant.
Once created, use it as the first argument in the log statement:

[source, java, indent=0]
----
include::example$manual/markers/MarkerExample.java[tag=use-marker]
----

If you use the <<example-configuration,configuration example below>>, one can see the following log statement on your console:

[source, text]
----
include::example$manual/markers/marker-filtering.log[tag=use-marker]
----

[#hierarchy]
=== Parent and child markers

A marker can have zero or more parent markers, allowing for a hierarchy of markers.
To create such a hierarchy, you must use the `addParents()` method on the `Marker` object after you make the child marker.

[source, java, indent=0]
----
include::example$manual/markers/MarkerExample.java[tag=create-marker-parent]
----

Child markers do not differ from simple markers; one must pass them on as the first argument of a logging call.

[source, java, indent=0]
----
include::example$manual/markers/MarkerExample.java[tag=use-marker-parent]
----

Messages marked with children's markers behave as if they were both marked with the children's marker and all its parents.
If you use the <<example-configuration,configuration example below>>, you'll see the following log statement on your console:

[source, text]
----
include::example$manual/markers/marker-filtering.log[tag=use-marker-parent]
----

[#configuring-log4j]
== Configuring filtering

Developers can use markers to filter the log statements delivered to log files.
Marker processing is supported at least by
https://logback.qos.ch/manual/filters.html#TurboFilter[Logback]
and the Log4j Core logging backends.
We will discuss only the configuration of the latter.

To filter messages by marker, you need to add
xref:manual/filters.adoc#MarkerFilter[`MarkerFilter`]
to your configuration file.
For example, one can use the snippet below to redirect all SQL-related logs to the `SQL_LOG` appender:

[[example-configuration]]
[tabs,opts=sync]
====
XML::
+
[source, xml]
----
include::example$manual/markers/log4j2.xml[tag=logger]
----

JSON::
+
[source, json]
----
include::example$manual/markers/log4j2.json[tag=logger]
----

YAML::
+
[source, yaml]
----
include::example$manual/markers/log4j2.yaml[tag=logger]
----

Java properties::
+
[source, properties]
----
include::example$manual/markers/log4j2.properties[tag=logger]
----
====

<1> Match all messages from `example` package from all levels
<2> Only allow messages marker with `SQL` or one of its children to be sent to the `SQL_LOG` appender.

[#pitfalls]
== Pitfalls

It is important to note that marker names must be unique, as Log4j registers them permanently by name.
Developers should avoid generic marker names, as they may conflict with
those provided by third parties. Except, of course, if the user is aware of the implications.

While it is possible to add or remove parent markers dynamically through the `setParents()` method,
it is generally advisable to set the parents when the marker is created for efficiency and performance reasons.

It is also worth noting that markers without parents are more efficient to evaluate
than markers with multiple parents. It is generally a good idea to avoid
complex hierarchies of markers where possible.

[#complete-example]
== Complete example

To try the examples on this page:

* add
{antora-examples-url}/manual/markers/MarkerExample.java[MarkerExample.java]
to the `src/main/java/example` folder of your project,
* add
{antora-examples-url}/manual/markers/log4j2.xml[log4j2.xml]
to the `src/main/resources` folder of your project.
