////
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
////
= Messages

Unlike other logging APIs, which either restrict the description of log events to (possibly interpolated) Java
https://docs.oracle.com/javase/{java-target-version}/docs/api/java/lang/String.html[`String`]s
or allow generic Java
https://docs.oracle.com/javase/{java-target-version}/docs/api/java/lang/Object.html[`Object`]s,
the Log4j API encapsulates every log message into the logging-specific
link:../javadoc/log4j-api/org/apache/logging/log4j/message/Message.html[`Message`]
interface, before passing it to the logging backend. Such an approach opens to developers a wide range of customization possibilities.

[#anatomy-log-event]
== Anatomy of a logging event

Logging events are complex objects that contain many fields that can be classified into three categories:

. Some fields are provided explicitly, in a
link:../javadoc/log4j-api/org/apache/logging/log4j/Logger.html[`Logger`]
method call.
The most important are the log level and the **log message**, which is a description of what happened addressed to humans.
Log4j API provides a rich set of methods to specify log messages, which will be described in this chapter.

. Some fields are contextual and is either provided explicitly by developers of other parts of the application (see
xref:manual/thread-context.adoc[Thread context])
or is injected by Java instrumentation.

. The last category of fields is those that are computed automatically by the logging backend you use.

For clarity's sake let us look at a possible log event formatted as JSON:

[source,json]
----
include::example$manual/messages/log-event.json[]
----

<1> Explicitly supplied fields:
`log.level`:: The xref:manual/customloglevels.adoc[log level] of the event, either explicitly provided as an argument to the logging call or implied by the name of the logging method,
`message`:: The **log message** that describes what happened.
`error.*`:: An _optional_
https://docs.oracle.com/javase/{/docs/api/java/lang/Throwable.html[`Throwable`] explicitly passed as an argument to the logging call.
`marker`:: An _optional_ xref:manual/markers.adoc[marker] explicitly passed as an argument to the logging call.
`log.logger`:: The xref:manual/api.adoc#logger-names[logger name] provided explicitly to `LogManager.getLogger()` or inferred by Log4j API.

<2> Contextual fields:
`tags`:: The stack of xref:manual/thread-context.adoc#nested-diagnostic-context[nested diagnostic context] messages.
`labels`:: The key/value pairs of the current xref:manual/thread-context.adoc#mapped-diagnostic-context[mapped diagnostic context].

<3> Logging backend specific fields.
In case you are using Log4j Core, the following fields can be automatically generated:
`@timestamp`:: The timestamp, when the log event occurs.
`log.origin.*`:: The xref:manual/layouts.adoc#LocationInformation[location] of the logging call in the source code.
`process.thread.*`:: The Java thread that generates the logging event.

== Creating log messages

While internally Log4j uses `Message` objects, the `Logger` interface provides various shortcut methods to create the most commonly used messages:

* To create a <<SimpleMessage,`SimpleMessage`>> from a `String` argument, the following logger calls are equivalent:
+
[source,java,indent=0]
----
include::example$manual/messages/MessagesExample.java[tag=simple]
----

* To create a <<ParameterizedMessage,`ParameterizedMessage`>> from a format `String` and an array of object parameters, the following logger calls are equivalent:
+
[source,java,indent=0]
----
include::example$manual/messages/MessagesExample.java[tag=parameterized]
----

In small and austere environments, this is sufficient. However, in more complex scenarios,
the string one wants to log may require more complex construction.

Imagine a scenario that uses a domain event to signal authentication failures:

[source,java]
----
record LoginFailureEvent(String userName, InetSocketAddress remoteAddress) {}
----

When the developer wants to log a message reporting the event,
we can see that the string construction becomes more challenging to read:

[source,java,indent=0]
----
include::example$manual/messages/MessagesExample.java[tag=complex]
----

By extending the `Message` interface, developers can simplify the reporting of a login failure:

[source,java,indent=0]
----
include::example$manual/messages/MessagesExample.java[tag=loginFailure]
----

<1> Developers need to implement the `Message` interface.
<2> The `getFormattedMessage()` provides the `String` to be logged.

The code is then reusable, by simply calling:

[source,java,indent=0 ]
----
include::example$manual/messages/MessagesExample.java[tag=complex-message]
----

== Message types

Log4j provides several message types that developers can use to create log messages.

[#FormattedMessage]
=== FormattedMessage

The message pattern passed to a
link:../javadoc/log4j-api/org/apache/logging/log4j/message/FormattedMessage.html[`FormattedMessage`]
undergoes a series of checks to determine the appropriate formatting method.

- First, the pattern is checked for a valid `java.text.MessageFormat` pattern.
- If it is, a `MessageFormatMessage` is used for formatting.
- If it is not, the pattern is then checked for any tokens that are valid format specifiers for `String.format()`.
A `StringFormattedMessage` is used to format the message when Log4j finds such tokens.
- Finally, if the pattern does not match either of these formats, a `ParameterizedMessage` is used for formatting.

[#LocalizedMessage]
=== LocalizedMessage

link:../javadoc/log4j-api/org/apache/logging/log4j/message/LocalizedMessage.html[`LocalizedMessage`]
is provided primarily to provide compatibility with Log4j 1.x.

Generally, the best approach to localization is to have the client's UI render the events in the client's locale.

`LocalizedMessage` incorporates a `ResourceBundle` and allows the message pattern parameter
to be the key to the message pattern in the bundle.

If no bundle is specified, `LocalizedMessage` will attempt to locate a bundle
with the name of the Logger used to log the event. The message retrieved
from the bundle will be formatted using a FormattedMessage.

[#LoggerNameAwareMessage]
=== LoggerNameAwareMessage

`LoggerNameAwareMessage` is an interface with a `setLoggerName()` method.

This method will be called during event construction so that the Message
has the name of the Logger used to log the event when Log4j formats the message.

[#MapMessage]
=== MapMessage

A `MapMessage` contains a Map of String keys and values.

`MapMessage` implements `FormattedMessage` and accepts the following format specifiers:

- "XML" - format the Map as XML
- "JSON" - format the Map as JSON
- "JAVA" - format the Map as a Java object

Otherwise, it will format the Map as documented in
https://docs.oracle.com/javase/7/docs/api/java/util/AbstractMap.html#toString()[`java.util.AbstractMap.toString()`].

Some appenders convert the `MapMessage` objects differently when there is no layout:

* JMS Appender converts to a JMS `javax.jms.MapMessage`.
* xref:manual/appenders.adoc#JDBCAppender[JDBC Appender] converts to values in a SQL INSERT statement
* xref:manual/appenders.adoc#NoSQLAppenderMongoDBMain[MongoDB Appender] converts to fields in MongoDB object

[#MessageFormatMessage]
=== MessageFormatMessage

link:../javadoc/log4j-api/org/apache/logging/log4j/message/MessageFormatMessage.html[`MessageFormatMessage`]
handles messages that use a
https://docs.oracle.com/javase/7/docs/api/java/text/MessageFormat.html[conversion format].

While this `Message` has more flexibility than `ParameterizedMessage,` it is also about two times slower.

[#MultiformatMessage]
=== MultiformatMessage

A `MultiformatMessage` has the `getFormats()` and `getFormattedMessage()` method that accepts an array of format Strings.

Layouts may use the `getFormats()` method to provide information on the formatting options the message supports.
The Layout may then call `getFormattedMessage()` with one or more formats.
The message will be shown in the default format when the format name is not recognized.

For example, the `StructuredDataMessage` accepts the "XML" format name to
format the message as XML instead of the default RFC5424 format.

[#ObjectMessage]
=== ObjectMessage

Formats an `Object` by calling its `toString()` method.

Since Log4j 2.6, low-garbage or garbage-free layouts call the `formatTo(StringBuilder)` method instead.

[#ParameterizedMessage]
=== ParameterizedMessage

link:../javadoc/log4j-api/org/apache/logging/log4j/message/ParameterizedMessage.html[`ParameterizedMessage`]
handles messages that contain "\{}" in the format to represent replaceable tokens and the replacement parameters.

[#ReusableObjectMessage]
=== ReusableObjectMessage

`ReusableObjectMessage` provides functionally equivalent to <<ObjectMessage>>.

Log4j uses this message in garbage-free mode to pass logged Objects to the Layout and Appenders.

[#ReusableParameterizedMessage]
=== ReusableParameterizedMessage

`ReusableParameterizedMessage` provides functionally equivalent to <<ParameterizedMessage>>.

Log4j uses this message in garbage-free mode to handle messages containing `{}` in the format representing replaceable tokens and the replacement parameters.

[#ReusableSimpleMessage]
=== ReusableSimpleMessage

`ReusableSimpleMessage` provides functionally equivalent to <<SimpleMessage>>.

Log4j uses this message in garbage-free mode to pass logged `String` and `CharSequence` objects to the Layout and Appenders.

[#SimpleMessage]
=== SimpleMessage

`SimpleMessage` contains a `String` or `CharSequence` that requires no formatting.

[#StringFormattedMessage]
=== StringFormattedMessage

link:../javadoc/log4j-api/org/apache/logging/log4j/message/StringFormattedMessage.html[`StringFormattedMessage`]
handles messages that use a
https://docs.oracle.com/javase/7/docs/api/java/util/Formatter.html#syntax[conversion format]
that is compliant with
https://docs.oracle.com/javase/7/docs/api/java/lang/String.html#format(java.lang.String,%20java.lang.Object...)[java.lang.String.format()].

This message is more flexible than `ParameterizedMessage` but 5 to 10 times slower.

[#StructuredDataMessage]
=== StructuredDataMessage

link:../javadoc/log4j-api/org/apache/logging/log4j/message/StructuredDataMessage.html[`StructuredDataMessage`]
allows applications to add items to a `Map` and set the ID to allow Log4j to format the message as a "Structured Data Element."

See: http://tools.ietf.org/html/rfc5424[RFC 5424] for details.

[#ThreadDumpMessage]
=== ThreadDumpMessage

If a `ThreadDumpMessage` is logged, Log4j generates stack traces for all threads.
These stack traces will include any held locks.

[#TimestampMessage]
=== TimestampMessage

A `TimestampMessage` provides a `getTimestamp()` method that Log4j calls during event construction.
The timestamp in the Message will be used instead of the current timestamp.

== Performance and benefits

Although it may initially seem counterintuitive, there is no performance benefit to using strings instead of messages.
Testing has shown that modern JVMs can create and destroy log events quickly,
especially when encapsulating complex tasks in the `Message` object instead of the application.

Applications that care about
xref:manual/garbagefree.adoc[garbage-free logging]
should consider implementing both the `Message` and
link:../javadoc/log4j-api/org/apache/logging/log4j/util/StringBuilderFormattable.html[`StringBuilderFormattable`],
which allows to format a message without the creation of temporary `String` objects.

Implementing `StringBuilderFormattable` is straightforward:

[source,java,indent=0]
----
include::example$manual/messages/StringBuilderFormattableExample.java[tag=loginFailure]
----

<1> Developers need to implement both the `Message` and `StringBuilderformattable` interface.
<2> The `formatTo()` method formats the message directly into a buffer.
<3> The `getFormattedMessage()` method can be easily implemented in terms of `formatTo()`.