////
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
////

= Simple Logger

Even though Log4j Core is the reference implementation of xref:manual/api.adoc[Log4j API], Log4j API itself also provides a very minimalist implementation: link:../javadoc/log4j-api/org/apache/logging/log4j/simple/SimpleLogger.html[`SimpleLogger`].
This is a convenience for environments where either a fully-fledged logging implementation is missing, or cannot be included for other reasons.
`SimpleLogger` is the default Log4j API implementation if no other is available in the classpath.

[#config]
== Configuration

[#logger]
=== Logger

`SimpleLogger` can be configured using the following system properties:

include::partial$manual/systemproperties/properties-simple-logger.adoc[leveloffset=+2]

[#thread-context]
=== Thread context

For the configuration of the thread context,
Simple Logger supports a subset of the properties supported by Log4j Core:

include::partial$manual/systemproperties/properties-thread-context-simple-logger.adoc[leveloffset=+2]