////
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
////

= Using Log4j in a Jakarta EE environment

[#web-applications]
== Integrating with Web Applications

[NOTE]
====
To avoid problems, some Log4j API and Log4j Core features are automatically disabled, when running in a Jakarta EE environment. Most notably:

- the usage of `ThreadLocal` for object pooling is disabled,
- a web-safe implementation of
link:../javadoc/log4j-api/org/apache/logging/log4j/spi/ThreadContextMap.html[`ThreadContextMap`] is used,
- JMX notifications are sent synchronously,
- the JVM shutdown hook is disabled.

See xref:manual/systemproperties.adoc#log4j2.isWebapp[`log4j2.isWebapp`] for more details.
====

Using a logging implementation like **Log4j Core** in a Jakarta EE application requires particular care.
Since the lifecycle of a container or web application is independent of the lifecycle of the JVM, it's important for logging resources to be properly cleaned up (database connections closed, files closed, etc.) when the container or web application shuts down.

To properly synchronize the lifecycles of Log4j Core and Jakarta EE applications an additional **Log4j Web** artifact is provided.

[#log4j-jakarta-web-installation]
=== Installation

In order to install Log4j Web in your Web application, you need to add it as runtime dependency:

include::partial$manual/dependencies-log4j-jakarta-web.adoc[]

If you are writing a Servlet 3.0 or later application, Apache Log4j Web will register a
https://jakarta.ee/specifications/servlet/5.0/apidocs/jakarta/servlet/servletcontainerinitializer[`ServletContainerInitializer`]
that takes care of configuring the Log4j lifecycle for you. Under the hood this will:

* initialize Log4j Core with the correct configuration file,
* register a `Log4jServletContextListener` to automatically shut down Log4j Core, when the application shuts down,
* register a `Log4jServletFilter` to enable the xref:manual/lookups.adoc#WebLookup[web lookup].

[WARNING]
====
While the Servlet Specification allows web fragments to automatically add context listeners, it does not give any guarantees regarding the order in which those listeners are executed
(cf. https://jakarta.ee/specifications/servlet/5.0/jakarta-servlet-spec-5.0#Assembling_the_descriptor[section 8.2.3]).

If other context listeners in your application use logging, you need to make sure that `Log4jServletContextListener` is the last listener to be executed at shutdown.
In order to do it you must create a `web.xml` descriptor and add the `Log4jServletContextListener` explicitly as **first** context listener:

[source,xml,indent=0]
----
include::example$manual/webapp/web.xml[tag=context-listener]
----
====

==== Manual installation

If you are maintaining an older Servlet 2.5 (or earlier) application or if you disabled

[source,xml,indent=0]
----
include::example$manual/webapp/web.xml[tags=context-listener;filter]
----

[#configuration]
=== Configuration

Log4j Web provides many configuration options to finely tune its installation.
These configuration options should be specified as
https://jakarta.ee/specifications/servlet/5.0/jakarta-servlet-spec-5.0#initialization-parameters[servlet context initialization parameters].

[id=isLog4jAutoInitializationDisabled]
==== `isLog4jAutoInitializationDisabled`

[cols="1h,5"]
|===
| Type          | `boolean`
| Default value | `false`
|===

If set to `true`, the `Log4jServletContainerInitializer` will be disabled, which prevents the automatic registration of both the `Log4jServletContextListener` and `Log4jServletFilter`.

[id=isLog4jAutoShutdownDisabled]
==== `isLog4jAutoShutdownDisabled`

[cols="1h,5"]
|===
| Type          | `boolean`
| Default value | `false`
|===

If set to `true`, the `Log4jServletContextListener` will not register a `Log4jServletContextListener` to handle the web application shut down.

[id=log4j.stop.timeout.timeunit]
==== `log4j.stop.timeout.timeunit`

[cols="1h,5"]
|===
| Type
| https://docs.oracle.com/javase/{java-target-version}/docs/api/java/util/concurrent/TimeUnit.html[`TimeUnit`]

| Default value
| https://docs.oracle.com/javase/{java-target-version}/docs/api/java/util/concurrent/TimeUnit.html#SECONDS[`SECONDS`]
|===

The `TimeUnit` to use for the shut-down delay.

[id=log4j.stop.timeout]
==== `log4j.stop.timeout`

[cols="1h,5"]
|===
| Type
| `long`

| Default value
| `30`
|===

[id=log4jContextName]
==== `log4jContextName`

[cols="1h,5"]
|===
| Type
| `String`

| Default value
| _automatically computed_
|===

Specifies the name of the logger context to use.

If <<log4j-jakarta-web-jndi-configuration,`JndiContextSelector`>> is used, this parameter **must** be explicitly provided. Otherwise, the default value is:

. the servlet context name, if present,
. the servlet context path, including the leading `/`, otherwise.

[id=isLog4jContextSelectorNamed]
==== `isLog4jContextSelectorNamed`

[cols="1h,5"]
|===
| Type
| `boolean`

| Default value
| `false`
|===

Must be set to `true` to use the <<log4j-jakarta-web-jndi-configuration,JNDI configuration>>.

[id=log4jConfiguration]
==== `log4jConfiguration`

[cols="1h,5"]
|===
| Type
| https://docs.oracle.com/javase/8/docs/api/java/net/URI.html[`URI`]

| Default value
| `false`
|===

The location of a Log4j Core configuration file.
If the provided value is not an **absolute** URI, Log4j interprets it as:

. path to a
https://jakarta.ee/specifications/servlet/5.0/apidocs/jakarta/servlet/servletcontext#getResource(java.lang.String)[servlet context resource], if it exists,
. path to a file, if it exists,
. path to a
https://docs.oracle.com/javase/8/docs/api/java/lang/ClassLoader.html#getResource-java.lang.String-[classpath resource], otherwise.

If no value is provided:

. Log4j Web looks for a servlet context resource named `/WEB-INF/log4j2-<contextName>.<extension>`, where `<contextName>` is the name of the logger context,
. if no such file exists it looks for a servlet context resource named `/WEB-INF/log4j2.<extension>`,
. otherwise it searches for a configuration file on the classpath using the usual https://logging.apache.org/log4j/2.x/manual/configuration.html#automatic-configuration[automatic configuration procedure].

[#async]
=== Asynchronous Requests and Threads

In order for the
xref:manual/lookups.adoc#WebLookup[web lookup]
to work correctly, Log4j must be able to always identify the `ServletContext` used by the current thread.
When standard requests, forwards, includes, and error resources are processed, the `Log4jServletFilter` binds the `LoggerContext` to the thread handling the request, and you don't have to do anything.

The handling of asynchronous requests is however more tricky, since it allows you to execute code on threads that were not prepared by `Log4jServletFilter`.
Such a situation occurs for example, if your code was started using the
https://jakarta.ee/specifications/servlet/5.0/apidocs/jakarta/servlet/asynccontext#start(java.lang.Runnable)[`AsyncContext.start(Runnable)`]
method.

To successfully propagate the logger context along asynchronous calls, the
link:../javadoc/log4j-jakarta-web/org/apache/logging/log4j/web/WebLoggerContextUtils.html[`WebLoggerContextUtils`]
helper class is made available.
Using this class you can either decorate a `Runnable` with method calls that bind the appropriate logger context to the thread:

[source,java,indent=0]
----
include::example$manual/webapp/AsyncServlet.java[tag=automatic]
----

or, if more flexibility is required, you can apply the same logic by using
link:../javadoc/log4j-jakarta-web/org/apache/logging/log4j/web/Log4jWebSupport.html[`Log4jWebSupport`]:

[source,java,indent=0]
----
include::example$manual/webapp/AsyncServlet.java[tag=manual]
----

[#application-server]
== Configuring an application server

[#jndi-configuration]
=== Using JNDI selectors

Log4j Core allows the usage of JNDI to coordinate the usage of logger contexts in a Jakarta EE application server.
In order to use this feature, you need to:

. Set the
xref:manual/systemproperties.adoc#log4j2.contextSelector[`log4j2.contextSelector`]
Log4j configuration property to ``org.apache.logging.log4j.core.selector.JndiContextSelector``,
. For security reasons you need to enable the selector, by setting the
xref:manual/systemproperties.adoc#log4j2.enableJndiContextSelector[`log4j2.enableJndiContextSelector`]
Log4j configuration property to `true`,
. Each web application needs to configure the servlet context parameter `isLog4jContextSelectorNamed` to `true` and provide a value for the `log4jContextName` servlet context parameter and `java:comp/env/log4j/context-name` JNDI environment entry:
+
[source,xml,indent=0]
----
include::example$manual/webapp/jndi.xml[tag=jndi]
----
