package org.apache.logging.log4j.samples.dto;

import org.apache.logging.log4j.message.StructuredDataMessage;

/**
 * Interface that indicates the Class was generated by the DTOManager.
 */
public interface AuditEvent {

    void logEvent();
}
