////
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
////

include::../_constants.adoc[]

= Install Apache Log4j

Apache Log4j is distributed under the
https://www.apache.org/licenses/LICENSE-2.0.html[Apache License, version 2.0].

== Using a build system

The preferred way to use Log4j in your project is to use a build system as Maven.
Please add the following to your build systems configuration file `pom.xml` to use Log4j.


[source,xml,indent=0,role="primary"]
.Maven (pom.xml)
----
<dependencies>
  <dependency>
    <groupId>org.apache.logging.log4j</groupId>
    <artifactId>log4j-api</artifactId>
    <version>{project-version}</version>
  </dependency>
</dependencies>
<dependencies>
    <dependency>
    <groupId>org.apache.logging.log4j</groupId>
    <artifactId>log4j-core</artifactId>
    <version>{project-version}</version>
    </dependency>
</dependencies>
----

[source,indent=0,role="secondary"]
.Gradle (build.gradle)
----
compile 'org.apache.logging.log4j:log4j-api:{project-version}'
compile 'org.apache.logging.log4j:log4j-core:{project-version}'
----

[source,xml,indent=0,role="secondary"]
.Ivy (ivy.xml)
----
<dependencies>
<dependency org="org.apache.logging.log4j" name="log4j-api" rev="{project-version}" />
<dependency org="org.apache.logging.log4j" name="log4j-core" rev="{project-version}" />
</dependencies>
----

== Manual Download

The link in the Mirrors column should display a list of available
mirrors with a default selection based on your inferred location. If you
do not see that page, try a different browser. The checksum and
signature are links to the originals on the main distribution server.

|===
|Distribution |Mirrors |Checksum |Signature

|Apache Log4j binary (tar.gz)
|https://www.apache.org/dyn/closer.lua/logging/log4j/{project-version}/apache-log4j-{project-version}-bin.tar.gz[apache-log4j-{project-version}-bin.tar.gz]
|https://www.apache.org/dist/logging/log4j/{project-version}/apache-log4j-{project-version}-bin.tar.gz.sha512[apache-log4j-{project-version}-bin.tar.gz.sha512]
|https://www.apache.org/dist/logging/log4j/{project-version}/apache-log4j-{project-version}-bin.tar.gz.asc[apache-log4j-{project-version}-bin.tar.gz.asc]

|Apache Log4j binary (zip)
|https://www.apache.org/dyn/closer.lua/logging/log4j/{project-version}/apache-log4j-{project-version}-bin.zip[apache-log4j-{project-version}-bin.zip]
|https://www.apache.org/dist/logging/log4j/{project-version}/apache-log4j-{project-version}-bin.zip.sha512[apache-log4j-{project-version}-bin.zip.sha512]
|https://www.apache.org/dist/logging/log4j/{project-version}/apache-log4j-{project-version}-bin.zip.asc[apache-log4j-{project-version}-bin.zip.asc]

|Apache Log4j source (tar.gz)
|https://www.apache.org/dyn/closer.lua/logging/log4j/{project-version}/apache-log4j-{project-version}-src.tar.gz[apache-log4j-{project-version}-src.tar.gz]
|https://www.apache.org/dist/logging/log4j/{project-version}/apache-log4j-{project-version}-src.tar.gz.sha512[apache-log4j-{project-version}-src.tar.gz.sha512]
|https://www.apache.org/dist/logging/log4j/{project-version}/apache-log4j-{project-version}-src.tar.gz.asc[apache-log4j-{project-version}-src.tar.gz.asc]

|Apache Log4j source (zip)
|https://www.apache.org/dyn/closer.lua/logging/log4j/{project-version}/apache-log4j-{project-version}-src.zip[apache-log4j-{project-version}-src.zip]
|https://www.apache.org/dist/logging/log4j/{project-version}/apache-log4j-{project-version}-src.zip.sha512[apache-log4j-{project-version}-src.zip.sha512]
|https://www.apache.org/dist/logging/log4j/{project-version}/apache-log4j-{project-version}-src.zip.asc[apache-log4j-{project-version}-src.zip.asc]
|===

It is essential that you verify the integrity of the downloaded files
using the PGP or SHA512 signatures. Please read
https://httpd.apache.org/dev/verification.html[Verifying Apache HTTP
Server Releases] for more information on why you should verify our
releases.

The PGP signatures can be verified using PGP or GPG. First download the
https://downloads.apache.org/logging/KEYS[KEYS] as well as the asc
signature file for the relevant distribution. Make sure you get these
files from the https://www.apache.org/dist/logging/[main distribution
directory], rather than from a mirror. Then verify the signatures using

[source,sh,subs=attributes]
----
gpg --import KEYS
gpg --verify apache-log4j-{project-version}-bin.zip.asc
----

Alternatively, you can verify the SHA512 signature on the files. A unix
program called sha512sum is included in many unix distributions.

[#requirements]
== Requirements

The Apache Log4j runtime requires a minimum of Java 17.
See the link:http://logging.apache.org/2.x[Log4j 2 website] for the latest releases supporting Java 6, 7, and 8.

== Previous Releases

All previous releases of Apache log4j can be found in the
https://archive.apache.org/dist/logging/log4j/[ASF archive repository]. Of course, all releases are availble for
use as dependencies from the https://search.maven.org/search?q=org.apache.logging.log4j[Maven Central Repository]

== Using Apache Log4j on your classpath

To use Log4j in your application make sure that the API, Plugins, and Core
jars are in the application’s classpath. Add the dependencies listed
below to your classpath.

* log4j-api-{project-version}.jar
* log4j-plugins-{project-version}.jar
* log4j-core-{project-version}.jar

You can do this from the command line or a manifest file.
