////
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
////
= Documentation (legacy)

This is the legacy documentation migrated from the older versions of Log4j. These documents will not be updated any longer, and are provided for historical reference only.

* link:/manual/index.html[Introduction]
* link:/manual/architecture.html[Architecture]
* link:/manual/migration.html[Log4j 1.x Migration]

== Java API

* link:/manual/api.html[Java API]
* link:/manual/logbuilder.html[Log Builder]
* link:/manual/flowtracing.html[Flow Tracing]
* link:/manual/markers.html[Markers]
* link:/manual/eventlogging.html[Event Logging]
* link:/manual/messages.html[Messages]
* link:/manual/thread-context.html[ThreadContext]