////
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
////
= Log4j Transformation Tools

Log4j Transformation Tools is set of build utilities to transform source and binary artifacts that use Log4j 2.x libraries.
The full documentation is available on https://github.com/apache/logging-log4j-transform/blob/main/README.adoc[Github].

== Available Tools

https://github.com/apache/logging-log4j-transform/blob/main/log4j-transform-maven-plugin/README.adoc[Log4j Transform Maven Plugin]::
Apache Maven plugin that precomputes the location of logging statements to prevent expensive runtime lookup calls.

https://github.com/apache/logging-log4j-transform/blob/main/log4j-transform-maven-shade-plugin-extensions/README.adoc[Log4j Plugin Cache Transformer]::
resource transformer for the
https://maven.apache.org/plugins/maven-shade-plugin/[Apache Maven Shade Plugin]
that merges the plugin caches used by Log4j 2.x artifacts.

