////
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
////

= Support

The Apache Software Foundation does not employ individuals to develop and support any of its projects.
The individuals who contribute to Apache projects do it either as part of specific tasks assigned to them by their employer, on their own initiative to benefit their employer, or on their own free time.

[#discussions]
== User support

If you have questions like:

* _"How do I configure Log4j with the file appender?"_
* _"My layout is not working as expected; what should I do?"_
* _"How can I migrate from Log4j 1 with this custom configuration?"_

We urge you to first check our link:faq.html[FAQ] to see if it has already been answered.
If not, you can ask your questions on one of our official user support channels:

* https://github.com/apache/logging-log4j2/discussions[GitHub Discussions] (**experimental**)
* `log4j-user@logging.apache.org` mailing list (public | mailto:log4j-user-subscribe@logging.apache.org[subscribe] | mailto:log4j-user-unsubscribe@logging.apache.org[unsubscribe] | mailto:log4j-user@logging.apache.org[post] | https://lists.apache.org/list.html?log4j-user&#64;logging.apache.org[archive])

[WARNING]
====
**You are expected to be subscribed** to a mailing list to receive replies to your posted questions!
If you are not subscribed, when you post an email, it will be subject to moderation (hence, will be distributed with a delay) and the only way you would be able to follow the conversation is to use the mailing list archive.
====

[WARNING]
====
Messages sent to a public mailing list will be seen by many people and also re-published by 3rd party websites.
It is usually not possible to remove them.
Please **don't send mails containing confidential information** to public mailing lists.
For more information, please see the https://privacy.apache.org/policies/privacy-policy-public.html[privacy policy]
====
* http://stackoverflow.com[Stack Overflow] (use http://stackoverflow.com/questions/tagged/log4j[log4j] or http://stackoverflow.com/questions/tagged/log4j2[log4j2] tags)

== Maintainer discussions

Apache Log4j project officially uses mailing lists for discussions related to maintenance and development.

[WARNING]
====
**You are expected to be subscribed** to a mailing list to receive replies to your posted questions!
If you are not subscribed, when you post an email, it will be subject to moderation (hence, will be distributed with a delay) and the only way you would be able to follow the conversation is to use the mailing list archive.
====

If you have questions or feedback like:

* A class should have public visibility instead of package-scoped
* A plugin is missing configuration options
* You found a bug

then please contact us using the following mailing lists:

`dev@logging.apache.org` (public | mailto:dev-subscribe@logging.apache.org[subscribe] | mailto:dev-unsubscribe@logging.apache.org[unsubscribe] | mailto:dev@logging.apache.org[post] | https://lists.apache.org/list.html?dev&#64;logging.apache.org[archive])::
For _development_ discussions
(Please prefix subjects with `[log4j]` when starting a new thread!)

[WARNING]
====
Messages sent to a public mailing list will be seen by many people and also re-published by 3rd party websites.
It is usually not possible to remove them.
Please **don't send mails containing confidential information** to public mailing lists.
For more information, please see the https://privacy.apache.org/policies/privacy-policy-public.html[privacy policy]
====

`security@logging.apache.org` (private | mailto:security@logging.apache.org[post])::
For reporting unlisted **security vulnerabilities** or other unexpected behaviour that has a security impact

`private@logging.apache.org` (private | mailto:private@logging.apache.org[post])::
For the discussion of confidential topics within the Apache Logging Services project management committee.

[#issues]
== Issues

The Log4j project uses https://github.com/apache/logging-log4j2/issues[GitHub Issues] as its issue tracking system.
The old issue tracking system, https://issues.apache.org/jira/projects/LOG4J2[JIRA], is still accessible, though only recommended for issues that were already created there.

Issues get resolved in one of the following ways:

. The reporter or another interested party provides https://github.com/apache/logging-log4j2/pulls[a pull request] tagging the issue in its title
. A committer is interested in the issue and decides to work on it
. The reporter or another interested party sponsors one or more of xref:#sponsorship[the committers listed below] to encourage them to work on the issue

Created issues are subject to the following policy:

Quality::
Issues posted of insufficient quality will be removed

No protracted discussions::
Issues likely to result in protracted discussion must be posted to the mailing lists

No Questions::
Do not post questions as issues!
These will be removed, and you will be asked to post questions to the mailing lists instead.

[#sponsorship]
== Sponsorship

Sponsorship can be used simply as a way to say thank you for the work that has been done or as a way to encourage specific issues to be worked on.
In either case, while the Apache Logging Services project thanks you for your support, we cannot be responsible for any promises and/or contributions made by an individual committer, as individual commits must be reviewed and accepted by the project team.

=== Committers accepting GitHub Sponsorship

* https://github.com/carterkozak[Carter Kozak]
* https://github.com/garydgregory[Gary Gregory]
* https://github.com/jvz[Matt Sicker]
* https://github.com/ppkarwasz[Piotr P. Karwasz]
* https://github.com/rgoers[Ralph Goers]
* https://github.com/vy[Volkan Yazıcı]

[#commercial]
== Third-party commercial support

While neither the Apache Software Foundation nor the Apache Logging Services project provide any commercial support for the Log4j products, individual committers may collaborate with services that provide such support.

The following aims to be a list of all commercial support services involving one or more Log4j committers.

[#tidelift]
=== Tidelift

Some Log4j maintainers receive funding from Tidelift for their maintenance efforts.
See https://tidelift.com[the Tidelift website] for details.
