////
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
////
= Support

++++
<link rel="stylesheet" type="text/css" href="css/tables.css">
++++

The Apache Software Foundation does not employ individuals to develop and support any of its projects.
The individuals who contribute to Apache projects do it either as part of specific tasks assigned to them by their
employer, on their own initiative to benefit their employer, or on their own free time.

[#]
== Statement of Support for Older Releases

Log4j 1.x reached end-of-life in 2015. The Logging Services Project no longer provides ANY direct support for these
versions. Occasionally we do get security reports against Log4j 1.x and while we have created CVEs for these in
the past we do not guarantee we will always do so. The Logging Services team is aware that there are others who
are providing releases against forks of Log4j 1.x so any security issues found when using them should be reported to
the maintainers of those libraries.

Log4j 2.3.4 is the latest release that supports Java 6. No future releases are planned. A new release will ONLY be
provided should a very serious security issue be reported.

Log4j 2.12.4 is the latest release that supports Java 7. No future releases are planned. A new release will ONLY be
provided should a very serious security issue be reported.

Later releases of the Log4j 2.x series all require a minimum of Java 8. This branch is still in active development.

For future planning know that the Log4j team will generally provide support for a specific JDK version until its
usage drops below 10% as listed in the publicly available annual Java Version statistics provided by various vendors.
While Log4j officially only supports LTS versions of Java we will accept bug reports for versions newer than the
latest LTS version.


[#discussions]
== Discussions

Apache Log4j project officially uses following mailing lists for discussions:

`log4j-user@logging.apache.org` (public | mailto:log4j-user-subscribe@logging.apache.org[subscribe] | mailto:log4j-user-unsubscribe@logging.apache.org[unsubscribe] | mailto:log4j-user@logging.apache.org[post] | https://lists.apache.org/list.html?log4j-user@logging.apache.org[archive])::
For _questions_ related to the usage of Log4j components

`dev@logging.apache.org` (public | mailto:dev-subscribe@logging.apache.org[subscribe] | mailto:dev-unsubscribe@logging.apache.org[unsubscribe] | mailto:dev@logging.apache.org[post] | https://lists.apache.org/list.html?dev@logging.apache.org[archive])::
For _development_ discussions
(Please prefix subjects with `[log4j]` when starting a new thread!)

`security@logging.apache.org` (private | mailto:security@logging.apache.org[post])::
For reporting unlisted security vulnerabilities or other unexpected behaviour that has a security impact

`private@logging.apache.org` (private | mailto:private@logging.apache.org[post])::
For the discussion of confidential topics within the Apache Logging Services project management committee

You can alternatively post questions on Stack Overflow tagged with either http://stackoverflow.com/questions/tagged/log4j[log4j]
or http://stackoverflow.com/questions/tagged/log4j2[log4j2].
Note that *Stack Overflow is more casually monitored due to time constraints*.
It is fine if you want to post first to Stack Overflow and then if you don't get an answer to post to the mailing lists.

[#issues]
== Issues

The Log4j project uses https://github.com/apache/logging-log4j2/issues[GitHub Issues] as its issue tracking system.
The old issue tracking system, https://issues.apache.org/jira/projects/LOG4J2[JIRA], is still accessible, though only
recommended for issues that were already created there.

Issues get resolved in one of the following ways:

. The reporter or another interested party provides https://github.com/apache/logging-log4j2/pulls[a pull request]
tagging the issue in its title
. A committer is interested in the issue and decides to work on it
. The reporter or another interested party sponsors one or more of xref:#sponsorship[the committers listed below]
to encourage them to work on the issue

Created issues are subject to the following policy:

Quality::
Issues posted of insufficient quality will be removed

No protracted discussions::
Issues likely to result in protracted discussion must be posted to the mailing lists

No Questions::
Do not post questions as issues!
These will be removed, and you will be asked to post questions to the mailing lists instead.

[#sponsorship]
== Sponsorship

Sponsorship can be used simply as a way to say thank you for the work that has been done or as a way to encourage specific issues to be worked on.
In either case, while the Apache Logging Services project thanks you for your support, we cannot be responsible for any promises and/or contributions made by an individual committer, as individual commits must be reviewed and accepted by the project team.

=== Committers accepting GitHub Sponsorship

* https://github.com/carterkozak[Carter Kozak]
* https://github.com/garydgregory[Gary Gregory]
* https://github.com/jvz[Matt Sicker]
* https://github.com/ppkarwasz[Piotr P. Karwasz]
* https://github.com/rgoers[Ralph Goers]
* https://github.com/vy[Volkan Yazıcı]

[#commercial]
== Third-party commercial support

While neither the Apache Software Foundation nor the Apache Logging Services project provide any commercial support for the Log4j products, individual committers may collaborate with services that provide such support.

The following aims to be a list of all commercial support services involving one or more Log4j committers.

[#tidelift]
=== Tidelift

Some Log4j maintainers receive funding from Tidelift for their maintenance efforts.
See https://tidelift.com[the Tidelift website] for details.
