////
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
////

If you are mixing `String` concatenation and parameterized logging, you are doing something very wrong and dangerous!

* [ ] The format string of a parameterized statement should be a compile time constant!
An attacker could mangle your logs by inserting `{}` placeholders in the values!
Try these examples with `userId="{}\nbadUser"` and `reason="root logged in successfully"`
+
[source,java]
----
/* BAD! */ LOGGER.info("User " + userId + " logged out: {}", reason);
----

* [x] Use message parameters
+
[source,java]
----
/* GOOD */ LOGGER.info("User {} logged out: {}", userId, reason);
----
