////
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
////

[tabs]
====
Maven::
+
[source,xml,subs="+attributes"]
----
<!-- We assume you use `log4j-bom` for dependency management -->
<dependency>
  <groupId>org.apache.logging.log4j</groupId>
  <artifactId>log4j-jakarta-web</artifactId>
  <scope>runtime</scope>
</dependency>
----

Gradle::
+
[source,groovy,subs="+attributes"]
----
// We assume you use `log4j-bom` for dependency management
runtimeOnly 'org.apache.logging.log4j:log4j-jakarta-web'
----
====

.Click here if you are you using Jakarta EE 8 or any version of Java EE?
[%collapsible]
=====
Jakarta EE 8 and all Java EE applications servers use the legacy `javax` package prefix instead of `jakarta`.
If you are using those application servers, you should replace the dependencies above with:

[tabs]
====
Maven::
+
[source,xml,subs="+attributes"]
----
<!-- We assume you use `log4j-bom` for dependency management -->
<dependency>
  <groupId>org.apache.logging.log4j</groupId>
  <artifactId>log4j-web</artifactId>
  <scope>runtime</scope>
</dependency>
----

Gradle::
+
[source,groovy,subs="+attributes"]
----
// We assume you use `log4j-bom` for dependency management
runtimeOnly 'org.apache.logging.log4j:log4j-web'
----
====
=====