////
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
////

// tag::part1[]
[#extending]
== Extending

{plugin-extension-intro-component-name} relies on xref:manual/plugins.adoc[the Log4j plugin system] to compose the features it provides.
This makes it possible for users to extend the plugin-based feature set as they see fit.
// end::part1[]
// tag::part2[]
Following sections cover these in detail.

[#extending-plugins]
=== Plugin preliminaries

Log4j plugin system is the de facto extension mechanism embraced by various Log4j components, including {plugin-extension-intro-component-name}.
Plugins make it possible for extensible components to _receive_ feature implementations without any explicit links in between.
It is analogous to a https://en.wikipedia.org/wiki/Dependency_injection[dependency injection] framework, but curated for Log4j-specific needs.

In a nutshell, you annotate your classes with `@Plugin` and their (`static`) factory methods with `@PluginFactory`.
Last, you inform the Log4j plugin system to discover these custom classes.
This is done using running the `org.apache.logging.log4j.core.config.plugins.processor.PluginProcessor` annotation processor while building your project.
Refer to xref:manual/plugins.adoc[] for details.
// end::part2[]
