////
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
////

This module contains JMH-based performance tests for Log4j.
You can use the generated fat JAR to run the tests as follows:

[source,bash]
----
java -cp target/log4j-perf-test-*-uber.jar org.openjdk.jmh.Main <JMH-ARGS>
----

To list the available JMH arguments run:
[source,bash]
----
java -cp target/log4j-perf-test-*-uber.jar org.openjdk.jmh.Main -h
----

== Examples

`ThreadLocalVsPoolBenchmark`::
+
[source,bash]
----
java -cp target/log4j-perf-test-*-uber.jar org.openjdk.jmh.Main \
  -f 1 -wi 10 -i 20 \
  -tu ns -bm sample \
  ".*ThreadLocalVsPoolBenchmark.*"
----

`JsonTemplateLayoutBenchmark`::
+
[source,bash]
----
java -cp target/log4j-perf-test-*-uber.jar org.openjdk.jmh.Main \
  -f 2 \
  -wi 3 -w 20s \
  -i 5 -r 30s \
  -prof gc \
  -prof perfnorm \
  -prof "async:libPath=/path/to/libasyncProfiler.so;output=flamegraph" \
  -rf json -rff log4j-perf-test/target/JsonTemplateLayoutBenchmarkResult.json \
  ".*JsonTemplateLayoutBenchmark.*"
----
