/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache license, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the license for the specific language governing permissions and
 * limitations under the license.
 */
package org.apache.logging.log4j.instrument.log4j2;

import java.util.List;

import org.apache.logging.log4j.Level;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.apache.logging.log4j.Marker;
import org.apache.logging.log4j.MarkerManager;
import org.apache.logging.log4j.core.LogEvent;
import org.apache.logging.log4j.core.test.appender.ListAppender;
import org.apache.logging.log4j.message.Message;
import org.apache.logging.log4j.message.SimpleMessage;
import org.apache.logging.log4j.util.Supplier;

import static org.assertj.core.api.Assertions.assertThat;

public class LoggerConversionHandlerExample {

    private static final CharSequence CHAR_SEQUENCE = "(CharSequence)";
    private static final Message MESSAGE = new SimpleMessage("(Message)");
    private static final String STRING = "(String)";
    private static final Object OBJECT = "(Object)";
    private static final Object P0 = "(p0)";
    private static final Object P1 = "(p1)";
    private static final Object P2 = "(p2)";
    private static final Object P3 = "(p3)";
    private static final Object P4 = "(p4)";
    private static final Object P5 = "(p5)";
    private static final Object P6 = "(p6)";
    private static final Object P7 = "(p7)";
    private static final Object P8 = "(p8)";
    private static final Object P9 = "(p9)";
    private static final Object[] PARRAY = { "(...)" };
    private static final Supplier<?>[] SUPPLIERS = { () -> OBJECT };
    private static final Throwable THROWABLE = new RuntimeException();
    private static final Marker MARKER = MarkerManager.getMarker("MARKER");

    private static final Logger logger = LogManager.getLogger();

    public void testFatal(final ListAppender app) {
        app.clear();
        final String methodName = "testFatal";
        int lineNumber = 60; // current line number
        logger.fatal(CHAR_SEQUENCE);
        assertLocationEquals(methodName, ++lineNumber, app);
        logger.fatal(CHAR_SEQUENCE, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.fatal(MARKER, CHAR_SEQUENCE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.fatal(MARKER, CHAR_SEQUENCE, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.fatal(MESSAGE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.fatal(MESSAGE, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.fatal(MARKER, MESSAGE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.fatal(MARKER, MESSAGE, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.fatal(OBJECT);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.fatal(OBJECT, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.fatal(MARKER, OBJECT);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.fatal(MARKER, OBJECT, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.fatal(STRING);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.fatal(MARKER, STRING);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.fatal(STRING, P0);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.fatal(MARKER, STRING, P0);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.fatal(STRING, P0, P1);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.fatal(MARKER, STRING, P0, P1);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.fatal(STRING, P0, P1, P2);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.fatal(MARKER, STRING, P0, P1, P2);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.fatal(STRING, P0, P1, P2, P3);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.fatal(MARKER, STRING, P0, P1, P2, P3);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.fatal(STRING, P0, P1, P2, P3, P4);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.fatal(MARKER, STRING, P0, P1, P2, P3, P4);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.fatal(STRING, P0, P1, P2, P3, P4, P5);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.fatal(MARKER, STRING, P0, P1, P2, P3, P4, P5);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.fatal(STRING, P0, P1, P2, P3, P4, P5, P6);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.fatal(MARKER, STRING, P0, P1, P2, P3, P4, P5, P6);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.fatal(STRING, P0, P1, P2, P3, P4, P5, P6, P7);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.fatal(MARKER, STRING, P0, P1, P2, P3, P4, P5, P6, P7);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.fatal(STRING, P0, P1, P2, P3, P4, P5, P6, P7, P8);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.fatal(MARKER, STRING, P0, P1, P2, P3, P4, P5, P6, P7, P8);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.fatal(STRING, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.fatal(MARKER, STRING, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.fatal(STRING, PARRAY);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.fatal(MARKER, STRING, PARRAY);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.fatal(() -> MESSAGE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.fatal(() -> MESSAGE, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.fatal(MARKER, () -> MESSAGE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.fatal(MARKER, () -> MESSAGE, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.fatal(() -> OBJECT);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.fatal(() -> OBJECT, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.fatal(MARKER, () -> OBJECT);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.fatal(MARKER, () -> OBJECT, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.fatal(STRING, SUPPLIERS);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.fatal(MARKER, STRING, SUPPLIERS);
        assertLocationEquals(methodName, lineNumber += 2, app);
    }

    public void testError(final ListAppender app) {
        app.clear();
        final String methodName = "testError";
        int lineNumber = 158; // current line number
        logger.error(CHAR_SEQUENCE);
        assertLocationEquals(methodName, ++lineNumber, app);
        logger.error(CHAR_SEQUENCE, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.error(MARKER, CHAR_SEQUENCE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.error(MARKER, CHAR_SEQUENCE, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.error(MESSAGE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.error(MESSAGE, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.error(MARKER, MESSAGE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.error(MARKER, MESSAGE, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.error(OBJECT);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.error(OBJECT, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.error(MARKER, OBJECT);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.error(MARKER, OBJECT, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.error(STRING);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.error(MARKER, STRING);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.error(STRING, P0);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.error(MARKER, STRING, P0);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.error(STRING, P0, P1);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.error(MARKER, STRING, P0, P1);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.error(STRING, P0, P1, P2);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.error(MARKER, STRING, P0, P1, P2);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.error(STRING, P0, P1, P2, P3);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.error(MARKER, STRING, P0, P1, P2, P3);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.error(STRING, P0, P1, P2, P3, P4);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.error(MARKER, STRING, P0, P1, P2, P3, P4);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.error(STRING, P0, P1, P2, P3, P4, P5);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.error(MARKER, STRING, P0, P1, P2, P3, P4, P5);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.error(STRING, P0, P1, P2, P3, P4, P5, P6);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.error(MARKER, STRING, P0, P1, P2, P3, P4, P5, P6);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.error(STRING, P0, P1, P2, P3, P4, P5, P6, P7);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.error(MARKER, STRING, P0, P1, P2, P3, P4, P5, P6, P7);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.error(STRING, P0, P1, P2, P3, P4, P5, P6, P7, P8);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.error(MARKER, STRING, P0, P1, P2, P3, P4, P5, P6, P7, P8);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.error(STRING, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.error(MARKER, STRING, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.error(STRING, PARRAY);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.error(MARKER, STRING, PARRAY);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.error(() -> MESSAGE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.error(() -> MESSAGE, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.error(MARKER, () -> MESSAGE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.error(MARKER, () -> MESSAGE, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.error(() -> OBJECT);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.error(() -> OBJECT, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.error(MARKER, () -> OBJECT);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.error(MARKER, () -> OBJECT, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.error(STRING, SUPPLIERS);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.error(MARKER, STRING, SUPPLIERS);
        assertLocationEquals(methodName, lineNumber += 2, app);
    }

    public void testWarn(final ListAppender app) {
        app.clear();
        final String methodName = "testWarn";
        int lineNumber = 256; // current line number
        logger.warn(CHAR_SEQUENCE);
        assertLocationEquals(methodName, ++lineNumber, app);
        logger.warn(CHAR_SEQUENCE, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.warn(MARKER, CHAR_SEQUENCE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.warn(MARKER, CHAR_SEQUENCE, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.warn(MESSAGE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.warn(MESSAGE, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.warn(MARKER, MESSAGE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.warn(MARKER, MESSAGE, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.warn(OBJECT);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.warn(OBJECT, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.warn(MARKER, OBJECT);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.warn(MARKER, OBJECT, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.warn(STRING);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.warn(MARKER, STRING);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.warn(STRING, P0);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.warn(MARKER, STRING, P0);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.warn(STRING, P0, P1);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.warn(MARKER, STRING, P0, P1);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.warn(STRING, P0, P1, P2);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.warn(MARKER, STRING, P0, P1, P2);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.warn(STRING, P0, P1, P2, P3);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.warn(MARKER, STRING, P0, P1, P2, P3);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.warn(STRING, P0, P1, P2, P3, P4);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.warn(MARKER, STRING, P0, P1, P2, P3, P4);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.warn(STRING, P0, P1, P2, P3, P4, P5);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.warn(MARKER, STRING, P0, P1, P2, P3, P4, P5);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.warn(STRING, P0, P1, P2, P3, P4, P5, P6);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.warn(MARKER, STRING, P0, P1, P2, P3, P4, P5, P6);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.warn(STRING, P0, P1, P2, P3, P4, P5, P6, P7);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.warn(MARKER, STRING, P0, P1, P2, P3, P4, P5, P6, P7);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.warn(STRING, P0, P1, P2, P3, P4, P5, P6, P7, P8);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.warn(MARKER, STRING, P0, P1, P2, P3, P4, P5, P6, P7, P8);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.warn(STRING, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.warn(MARKER, STRING, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.warn(STRING, PARRAY);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.warn(MARKER, STRING, PARRAY);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.warn(() -> MESSAGE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.warn(() -> MESSAGE, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.warn(MARKER, () -> MESSAGE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.warn(MARKER, () -> MESSAGE, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.warn(() -> OBJECT);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.warn(() -> OBJECT, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.warn(MARKER, () -> OBJECT);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.warn(MARKER, () -> OBJECT, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.warn(STRING, SUPPLIERS);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.warn(MARKER, STRING, SUPPLIERS);
        assertLocationEquals(methodName, lineNumber += 2, app);
    }

    public void testInfo(final ListAppender app) {
        app.clear();
        final String methodName = "testInfo";
        int lineNumber = 354; // current line number
        logger.info(CHAR_SEQUENCE);
        assertLocationEquals(methodName, ++lineNumber, app);
        logger.info(CHAR_SEQUENCE, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.info(MARKER, CHAR_SEQUENCE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.info(MARKER, CHAR_SEQUENCE, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.info(MESSAGE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.info(MESSAGE, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.info(MARKER, MESSAGE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.info(MARKER, MESSAGE, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.info(OBJECT);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.info(OBJECT, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.info(MARKER, OBJECT);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.info(MARKER, OBJECT, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.info(STRING);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.info(MARKER, STRING);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.info(STRING, P0);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.info(MARKER, STRING, P0);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.info(STRING, P0, P1);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.info(MARKER, STRING, P0, P1);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.info(STRING, P0, P1, P2);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.info(MARKER, STRING, P0, P1, P2);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.info(STRING, P0, P1, P2, P3);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.info(MARKER, STRING, P0, P1, P2, P3);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.info(STRING, P0, P1, P2, P3, P4);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.info(MARKER, STRING, P0, P1, P2, P3, P4);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.info(STRING, P0, P1, P2, P3, P4, P5);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.info(MARKER, STRING, P0, P1, P2, P3, P4, P5);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.info(STRING, P0, P1, P2, P3, P4, P5, P6);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.info(MARKER, STRING, P0, P1, P2, P3, P4, P5, P6);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.info(STRING, P0, P1, P2, P3, P4, P5, P6, P7);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.info(MARKER, STRING, P0, P1, P2, P3, P4, P5, P6, P7);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.info(STRING, P0, P1, P2, P3, P4, P5, P6, P7, P8);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.info(MARKER, STRING, P0, P1, P2, P3, P4, P5, P6, P7, P8);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.info(STRING, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.info(MARKER, STRING, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.info(STRING, PARRAY);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.info(MARKER, STRING, PARRAY);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.info(() -> MESSAGE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.info(() -> MESSAGE, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.info(MARKER, () -> MESSAGE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.info(MARKER, () -> MESSAGE, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.info(() -> OBJECT);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.info(() -> OBJECT, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.info(MARKER, () -> OBJECT);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.info(MARKER, () -> OBJECT, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.info(STRING, SUPPLIERS);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.info(MARKER, STRING, SUPPLIERS);
        assertLocationEquals(methodName, lineNumber += 2, app);
    }

    public void testDebug(final ListAppender app) {
        app.clear();
        final String methodName = "testDebug";
        int lineNumber = 452; // current line number
        logger.debug(CHAR_SEQUENCE);
        assertLocationEquals(methodName, ++lineNumber, app);
        logger.debug(CHAR_SEQUENCE, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.debug(MARKER, CHAR_SEQUENCE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.debug(MARKER, CHAR_SEQUENCE, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.debug(MESSAGE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.debug(MESSAGE, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.debug(MARKER, MESSAGE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.debug(MARKER, MESSAGE, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.debug(OBJECT);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.debug(OBJECT, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.debug(MARKER, OBJECT);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.debug(MARKER, OBJECT, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.debug(STRING);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.debug(MARKER, STRING);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.debug(STRING, P0);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.debug(MARKER, STRING, P0);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.debug(STRING, P0, P1);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.debug(MARKER, STRING, P0, P1);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.debug(STRING, P0, P1, P2);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.debug(MARKER, STRING, P0, P1, P2);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.debug(STRING, P0, P1, P2, P3);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.debug(MARKER, STRING, P0, P1, P2, P3);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.debug(STRING, P0, P1, P2, P3, P4);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.debug(MARKER, STRING, P0, P1, P2, P3, P4);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.debug(STRING, P0, P1, P2, P3, P4, P5);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.debug(MARKER, STRING, P0, P1, P2, P3, P4, P5);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.debug(STRING, P0, P1, P2, P3, P4, P5, P6);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.debug(MARKER, STRING, P0, P1, P2, P3, P4, P5, P6);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.debug(STRING, P0, P1, P2, P3, P4, P5, P6, P7);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.debug(MARKER, STRING, P0, P1, P2, P3, P4, P5, P6, P7);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.debug(STRING, P0, P1, P2, P3, P4, P5, P6, P7, P8);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.debug(MARKER, STRING, P0, P1, P2, P3, P4, P5, P6, P7, P8);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.debug(STRING, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.debug(MARKER, STRING, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.debug(STRING, PARRAY);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.debug(MARKER, STRING, PARRAY);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.debug(() -> MESSAGE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.debug(() -> MESSAGE, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.debug(MARKER, () -> MESSAGE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.debug(MARKER, () -> MESSAGE, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.debug(() -> OBJECT);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.debug(() -> OBJECT, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.debug(MARKER, () -> OBJECT);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.debug(MARKER, () -> OBJECT, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.debug(STRING, SUPPLIERS);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.debug(MARKER, STRING, SUPPLIERS);
        assertLocationEquals(methodName, lineNumber += 2, app);
    }

    public void testTrace(final ListAppender app) {
        app.clear();
        final String methodName = "testTrace";
        int lineNumber = 550; // current line number
        logger.trace(CHAR_SEQUENCE);
        assertLocationEquals(methodName, ++lineNumber, app);
        logger.trace(CHAR_SEQUENCE, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.trace(MARKER, CHAR_SEQUENCE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.trace(MARKER, CHAR_SEQUENCE, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.trace(MESSAGE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.trace(MESSAGE, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.trace(MARKER, MESSAGE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.trace(MARKER, MESSAGE, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.trace(OBJECT);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.trace(OBJECT, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.trace(MARKER, OBJECT);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.trace(MARKER, OBJECT, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.trace(STRING);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.trace(MARKER, STRING);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.trace(STRING, P0);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.trace(MARKER, STRING, P0);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.trace(STRING, P0, P1);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.trace(MARKER, STRING, P0, P1);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.trace(STRING, P0, P1, P2);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.trace(MARKER, STRING, P0, P1, P2);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.trace(STRING, P0, P1, P2, P3);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.trace(MARKER, STRING, P0, P1, P2, P3);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.trace(STRING, P0, P1, P2, P3, P4);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.trace(MARKER, STRING, P0, P1, P2, P3, P4);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.trace(STRING, P0, P1, P2, P3, P4, P5);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.trace(MARKER, STRING, P0, P1, P2, P3, P4, P5);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.trace(STRING, P0, P1, P2, P3, P4, P5, P6);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.trace(MARKER, STRING, P0, P1, P2, P3, P4, P5, P6);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.trace(STRING, P0, P1, P2, P3, P4, P5, P6, P7);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.trace(MARKER, STRING, P0, P1, P2, P3, P4, P5, P6, P7);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.trace(STRING, P0, P1, P2, P3, P4, P5, P6, P7, P8);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.trace(MARKER, STRING, P0, P1, P2, P3, P4, P5, P6, P7, P8);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.trace(STRING, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.trace(MARKER, STRING, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.trace(STRING, PARRAY);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.trace(MARKER, STRING, PARRAY);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.trace(() -> MESSAGE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.trace(() -> MESSAGE, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.trace(MARKER, () -> MESSAGE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.trace(MARKER, () -> MESSAGE, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.trace(() -> OBJECT);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.trace(() -> OBJECT, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.trace(MARKER, () -> OBJECT);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.trace(MARKER, () -> OBJECT, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.trace(STRING, SUPPLIERS);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.trace(MARKER, STRING, SUPPLIERS);
        assertLocationEquals(methodName, lineNumber += 2, app);
    }

    public void testLog(final ListAppender app) {
        app.clear();
        final String methodName = "testLog";
        int lineNumber = 648; // current line number
        logger.log(Level.INFO, CHAR_SEQUENCE);
        assertLocationEquals(methodName, ++lineNumber, app);
        logger.log(Level.INFO, CHAR_SEQUENCE, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.log(Level.INFO, MARKER, CHAR_SEQUENCE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.log(Level.INFO, MARKER, CHAR_SEQUENCE, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.log(Level.INFO, MESSAGE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.log(Level.INFO, MESSAGE, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.log(Level.INFO, MARKER, MESSAGE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.log(Level.INFO, MARKER, MESSAGE, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.log(Level.INFO, OBJECT);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.log(Level.INFO, OBJECT, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.log(Level.INFO, MARKER, OBJECT);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.log(Level.INFO, MARKER, OBJECT, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.log(Level.INFO, STRING);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.log(Level.INFO, MARKER, STRING);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.log(Level.INFO, STRING, P0);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.log(Level.INFO, MARKER, STRING, P0);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.log(Level.INFO, STRING, P0, P1);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.log(Level.INFO, MARKER, STRING, P0, P1);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.log(Level.INFO, STRING, P0, P1, P2);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.log(Level.INFO, MARKER, STRING, P0, P1, P2);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.log(Level.INFO, STRING, P0, P1, P2, P3);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.log(Level.INFO, MARKER, STRING, P0, P1, P2, P3);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.log(Level.INFO, STRING, P0, P1, P2, P3, P4);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.log(Level.INFO, MARKER, STRING, P0, P1, P2, P3, P4);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.log(Level.INFO, STRING, P0, P1, P2, P3, P4, P5);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.log(Level.INFO, MARKER, STRING, P0, P1, P2, P3, P4, P5);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.log(Level.INFO, STRING, P0, P1, P2, P3, P4, P5, P6);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.log(Level.INFO, MARKER, STRING, P0, P1, P2, P3, P4, P5, P6);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.log(Level.INFO, STRING, P0, P1, P2, P3, P4, P5, P6, P7);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.log(Level.INFO, MARKER, STRING, P0, P1, P2, P3, P4, P5, P6, P7);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.log(Level.INFO, STRING, P0, P1, P2, P3, P4, P5, P6, P7, P8);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.log(Level.INFO, MARKER, STRING, P0, P1, P2, P3, P4, P5, P6, P7, P8);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.log(Level.INFO, STRING, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.log(Level.INFO, MARKER, STRING, P0, P1, P2, P3, P4, P5, P6, P7, P8, P9);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.log(Level.INFO, STRING, PARRAY);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.log(Level.INFO, MARKER, STRING, PARRAY);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.log(Level.INFO, () -> MESSAGE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.log(Level.INFO, () -> MESSAGE, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.log(Level.INFO, MARKER, () -> MESSAGE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.log(Level.INFO, MARKER, () -> MESSAGE, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.log(Level.INFO, () -> OBJECT);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.log(Level.INFO, () -> OBJECT, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.log(Level.INFO, MARKER, () -> OBJECT);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.log(Level.INFO, MARKER, () -> OBJECT, THROWABLE);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.log(Level.INFO, STRING, SUPPLIERS);
        assertLocationEquals(methodName, lineNumber += 2, app);
        logger.log(Level.INFO, MARKER, STRING, SUPPLIERS);
        assertLocationEquals(methodName, lineNumber += 2, app);
    }

    public void testFrames(final ListAppender app) {
        app.clear();
        final String methodName = "testFrames";
        final int lineNumber = 746; // Current line
        int i = 0;
        while (i < 2) {
            if (i < 1) {
                logger.debug(OBJECT);
                assertLocationEquals(methodName, lineNumber + 4, app);
            } else {
                logger.debug(OBJECT);
                assertLocationEquals(methodName, lineNumber + 7, app);
            }
            logger.debug(OBJECT);
            assertLocationEquals(methodName, lineNumber + 10, app);
            i++;
        }
        switch (i) {
            case 2:
                logger.debug(OBJECT);
                assertLocationEquals(methodName, lineNumber + 16, app);
                break;
        }
        for (; i >= 0; i--) {
            logger.debug(OBJECT);
            assertLocationEquals(methodName, lineNumber + 21, app);
        }
    }

    private static void assertLocationEquals(final String methodName, final int lineNumber, final ListAppender app) {
        final List<LogEvent> events = app.getEvents();
        assertThat(events).hasSize(1);
        final LogEvent event = events.get(0);
        assertThat(event.isIncludeLocation()).isFalse();
        assertThat(event.getSource()).isNotNull();
        final StackTraceElement location = event.getSource();
        assertThat(location.getClassName()).isEqualTo(LoggerConversionHandlerExample.class.getName());
        assertThat(location.getMethodName()).isEqualTo(methodName);
        assertThat(location.getFileName()).isEqualTo("LocationExample.java");
        assertThat(location.getLineNumber()).isEqualTo(lineNumber);
        app.clear();
    }
}
