////
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
////
[id=log4j.threadContext.enable]
== `log4j.threadContext.enable`

[cols="1h,5"]
|===
| Env. variable | LOG4J_THREAD_CONTEXT_ENABLE
| Type          | `boolean`
| Default value | `true`
|===

If `false`, the `ThreadContext` stack and map are disabled.

[id=log4j.threadContext.enableStack]
== `log4j.threadContext.enableStack`

[cols="1h,5"]
|===
| Env. variable | LOG4J_THREAD_CONTEXT_ENABLE_STACK
| Type          | `boolean`
| Default value | `true`
|===

If `false`, the `ThreadContext` stack is disabled.

[id=log4j.threadContext.map.enable]
== `log4j.threadContext.map.enable`

[cols="1h,5"]
|===
| Env. variable | LOG4J_THREAD_CONTEXT_MAP_ENABLE
| Type          | `boolean`
| Default value | `true`
|===

If `false`, the `ThreadContext` map is disabled.

// tag::gcfree[]

[id=log4j.threadContext.map.type]
== `log4j.threadContext.map.type`

[cols="1h,5"]
|===
| Env. variable
| LOG4J_THREAD_CONTEXT_MAP_TYPE

| Type
| {log4j2-url}/javadoc/log4j-api/org/apache/logging/log4j/spi/ThreadContextMap[Class<? extends ThreadContextMap>] or predefined constant

| Default value
| `WebApp`

(GC-free mode: `CopyOnWrite`)
|===

Fully specified class name of a custom {log4j2-url}/javadoc/log4j-api/org/apache/logging/log4j/spi/ThreadContextMap[ThreadContextMap] implementation class or one of the predefined constants:

NoOp:: to disable the thread context,
WebApp:: a web application-safe implementation, that only binds JRE classes to `ThreadLocal` to prevent memory leaks,
CopyOnWrite:: a copy-on-write implementation,
GarbageFree:: a garbage-free implementation.

[id=log4j.threadContext.map.garbageFree]
== `log4j.threadContext.map.garbageFree`

[cols="1h,5"]
|===
| Env. variable | LOG4J_THREAD_CONTEXT_MAP_GARBAGE_FREE
| Default value | `false`
|===

If set to `true` selects a garbage-free thread context map implementation.

// end::gcfree[]
