////
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
////
[id=log4j.jndi.enableContextSelector]
== `log4j.jndi.enableContextSelector`

[cols="1h,5"]
|===
| Env. variable | LOG4J_JNDI_ENABLE_CONTEXT_SELECTOR
| Type          | `boolean`
| Default value | `false`
|===

When `true` the `JndiContextSelector` is enabled for the `java:` protocol.
See
link:../../jakarta/log4j-jakarta-web.html#jndi[Web application]
for more details.

[id=log4j.jndi.enableJdbc]
== `log4j.jndi.enableJdbc`

[cols="1h,5"]
|===
| Env. variable | LOG4J_JNDI_ENABLE_JDBC
| Type          | `boolean`
| Default value | `false`
|===

When `true`, a Log4j JDBC Appender can use JNDI to retrieve a https://docs.oracle.com/javase/8/docs/api/javax/sql/DataSource.html[DataSource] using the `java:` protocol.

[id=log4j.jndi.enableJms]
== `log4j.jndi.enableJms`

[cols="1h,5"]
|===
| Env. variable | LOG4J_JNDI_ENABLE_JMS
| Type          | `boolean`
| Default value | `false`
|===

When `true`, a Log4j JMS Appender can use JNDI to retrieve the necessary components using the `java:` protocol.

[id=log4j.jndi.enableLookup]
== `log4j.jndi.enableLookup`

[cols="1h,5"]
|===
| Env. variable | LOG4J_JNDI_ENABLE_LOOKUP
| Type          | `boolean`
| Default value | `false`
|===

When `true`, the Log4j JNDI Lookup can use the `java:` protocol.