////
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
////
[id=log4j2.julLevelConverter]
== `log4j2.julLevelConverter`

[cols="1h,5"]
|===
| Env. variable | `LOG4J_JUL_LEVEL_CONVERTER`
| Type          | `Class<? extends LevelConverter>`
| Default value | `org.apache.logging.log4j.jul.DefaultLevelConverter`
|===

Fully qualified name of an alternative `org.apache.logging.log4j.jul.LevelConverter` implementation.

.Default level conversions
[%collapsible]
====
[cols="1m,1",id=default-level-conversions]
|===
| Java Level | Log4j Level

| https://docs.oracle.com/javase/{java-target-version}/docs/api/java/util/logging/Level.html#OFF[OFF]
| `OFF`

| https://docs.oracle.com/javase/{java-target-version}/docs/api/java/util/logging/Level.html#SEVERE[SEVERE]
| `ERROR`

| https://docs.oracle.com/javase/{java-target-version}/docs/api/java/util/logging/Level.html#WARNING[WARNING]
| `WARN`

| https://docs.oracle.com/javase/{java-target-version}/docs/api/java/util/logging/Level.html#INFO[INFO]
| `INFO`

| https://docs.oracle.com/javase/{java-target-version}/docs/api/java/util/logging/Level.html#CONFIG[CONFIG]
| custom `CONFIG` level with a numeric value of `450`

| https://docs.oracle.com/javase/{java-target-version}/docs/api/java/util/logging/Level.html#FINE[FINE]
| `DEBUG`

| https://docs.oracle.com/javase/{java-target-version}/docs/api/java/util/logging/Level.html#FINER[FINER]
| `TRACE`

| https://docs.oracle.com/javase/{java-target-version}/docs/api/java/util/logging/Level.html#FINEST[FINEST]
| custom `FINEST` level with a numeric value of `700`

| https://docs.oracle.com/javase/{java-target-version}/docs/api/java/util/logging/Level.html#ALL[ALL]
| `ALL`
|===
====

[id=log4j2.julLoggerAdapter]
== `log4j2.julLoggerAdapter`

[cols="1h,5"]
|===
| Env. variable | `LOG4J_JUL_LOGGER_ADAPTER`
| Type          | `Class<? extends AbstractLoggerAdapter>`
| Default value | `org.apache.logging.log4j.jul.ApiLoggerAdapter`
|===

Fully qualified class name of the `org.apache.logging.log4j.jul.AbstractLoggerAdapter` implementation to use.

This property allows users to choose between two implementations of the logging bridge:

`org.apache.logging.log4j.jul.CoreLoggerAdapter`::
It allows users to modify the Log4j Core configuration through the JUL https://docs.oracle.com/javase/{java-target-version}/docs/api/java/util/logging/Logger.html[`Logger`] interface.
It requires the usage of the
xref:manual/implementation.adoc[Log4j Core]
implementation.

`org.apache.logging.log4j.jul.ApiLoggerAdapter`::
It disables the level mutators in the JUL `Logger` interface.

[NOTE]
====
Since version 2.24.0 the default value changed to `ApiLoggerAdapter`.
If you need to modify log levels via JUL, you need to select `CoreLoggerAdapter` explicitly.
====