////
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
////
[id=log4j2.skipJansi]
== `log4j2.skipJansi`

[cols="1h,5"]
|===
| Env. variable | `LOG4J_SKIP_JANSI`
| Type          | `boolean`
| Default value | `true`
|===

If the following conditions are satisfied:

* Log4j runs on Windows,
* this property is set to `false`,

Log4j will use the JANSI library to color the output of the console appender.