[[log4j2.enableJndiContextSelector]]
== `log4j2.enableJndiContextSelector`

[cols="1h,5"]
|===
| Env. variable | LOG4J_ENABLE_JNDI_CONTEXT_SELECTOR
| Default value | ``false``
|===

When `true` the `JndiContextSelector` is enabled for the `java:` protocol.
See xref:manual/webapp.adoc#use-jndi-context-selector[Web application] for more details.

[[log4j2.enableJndiJdbc]]
== `log4j2.enableJndiJdbc`

[cols="1h,5"]
|===
| Env. variable | LOG4J_ENABLE_JNDI_JDBC
| Default value | ``false``
|===

When `true`, a Log4j JDBC Appender can use JNDI to retrieve a https://docs.oracle.com/javase/8/docs/api/javax/sql/DataSource.html[DataSource] using the `java:` protocol.

[[log4j2.enableJndiJms]]
== `log4j2.enableJndiJms`

[cols="1h,5"]
|===
| Env. variable | LOG4J_ENABLE_JNDI_JMS
| Default value | ``false``
|===

When `true`, a Log4j JMS Appender can use JNDI to retrieve the necessary components using the `java:` protocol.

[[log4j2.enableJndiLookup]]
== `log4j2.enableJndiLookup`

[cols="1h,5"]
|===
| Env. variable | LOG4J_ENABLE_JNDI_LOOKUP
| Default value | ``false``
|===

When `true`, the Log4j JNDI Lookup can use the `java:` protocol.