[[log4j2.contextSelector]]
== `log4j2.contextSelector`

[cols="1h,5"]
|===
| Env. variable | LOG4J_CONTEXT_SELECTOR
| Default value | `link:../javadoc/log4j-core/org/apache/logging/log4j/core/selector/ClassLoaderContextSelector[ClassLoaderContextSelector]`
|===

Specifies the fully qualified class name of the `ContextSelector` implementation to use.

The implementations available by default are:

link:../javadoc/log4j-core/org/apache/logging/log4j/core/selector/BasicContextSelector[BasicContextSelector]::
Creates a single logger context and synchronous loggers

link:../javadoc/log4j-core/org/apache/logging/log4j/core/async/BasicAsyncLoggerContextSelector[BasicAsyncLoggerContextSelector]::
Creates a single logger context and xref:manual/async.adoc[asynchronous loggers]

link:../javadoc/log4j-core/org/apache/logging/log4j/core/selector/ClassLoaderContextSelector[ClassLoaderContextSelector]::
Creates a separate logger context per classloader and synchronous loggers

link:../javadoc/log4j-core/org/apache/logging/log4j/core/async/AsyncLoggerContextSelector[AsyncLoggerContextSelector]::
Creates a separate logger context per classloader and xref:manual/async.adoc[asynchronous loggers]

link:../javadoc/log4j-core/org/apache/logging/log4j/core/osgi/BundleContextSelector[BundleContextSelector]::
Creates a separate logger context per OSGi bundle and synchronous loggers

link:../javadoc/log4j-core/org/apache/logging/log4j/core/selector/JndiContextSelector[JndiContextSelector]::
Creates loggers contexts based on a JNDI lookup and synchronous loggers See xref:manual/webapp.adoc#use-jndi-context-selector[Web application] for details.