[[log4j2.julLevelConverter]]
== `log4j2.julLevelConverter`

[cols="1h,5"]
|===
| Env. variable | LOG4J_JUL_LEVEL_CONVERTER
| Default value | `org.apache.logging.log4j.jul.DefaultLevelConverter`
|===


Fully qualified name of an alternative `org.apache.logging.log4j.jul.LevelConverter` implementation.

See xref:log4j-jul.adoc#default-level-conversions[Default Level Conversions] for the default implementation.

[[log4j2.julLoggerAdapter]]
== `log4j2.julLoggerAdapter`

[cols="1h,5"]
|===
| Env. variable | LOG4J_JUL_LOGGER_ADAPTER
| Default value | `depends on classpath`
|===


This property allows users to choose between two implementation of the logging bridge:

`org.apache.logging.log4j.jul.CoreLoggerAdapter`::
The default if `log4j-core` is found in the class path.
It allows users to modify the Log4j Core configuration through the JUL https://docs.oracle.com/javase/8/docs/api/java/util/logging/Logger.html[Logger] interface.

`org.apache.logging.log4j.jul.ApiLoggerAdapter`::
The default if `log4j-core` cannot be found in the class path.
It disables the level mutators in the JUL `Logger` interface.