[[log4j2.clock]]
== `log4j2.clock`

[cols="1h,5"]
|===
| Env. variable | LOG4J_CLOCK
| Default value | ``SystemClock``
|===

Specifies the link:../javadoc/log4j-core/org/apache/logging/log4j/core/util/Clock[Clock] implementation used to timestamp log events.

The built-in implementations are:

`SystemClock`:: uses the best available system clock as time source.
See https://docs.oracle.com/javase/{java-target-version}/docs/api/java/time/Clock.html#systemDefaultZone--[Clock#systemDefaultZone] for details.

`SystemMillisClock`:: same as `SystemClock`, but truncates the result to a millisecond.

`CachedClock`:: uses a separate thread to update the timestamp value.
See link:../javadoc/log4j-core/org/apache/logging/log4j/core/util/CachedClock[JavaDoc] for details.

`CoarseCachedClock`:: alternative implementation of `CachedClock` with a slightly lower precision.
See link:../javadoc/log4j-core/org/apache/logging/log4j/core/util/CoarseCachedClock[JavaDoc] for details.

[[log4j2.contextDataInjector]]
== `log4j2.contextDataInjector`

[cols="1h,5"]
|===
| Env. variable | LOG4J_CONTEXT_DATA_INJECTOR
| Default value | `depends on the `ThreadContextMap` implementation`
|===

Fully specified class name of a link:../javadoc/log4j-core/org/apache/logging/log4j/core/ContextDataInjector[ContextDataInjector] implementation.

The default implementation uses all implementations of link:../javadoc/log4j-core/org/apache/logging/log4j/core/util/ContextDataProvider[ContextDataProvider] registered with `ServiceLoader`.

[[log4j2.logEventFactory]]
== `log4j2.logEventFactory`

[cols="1h,5"]
|===
| Env. variable | LOG4J_LOG_EVENT_FACTORY
| Default value | `link:../javadoc/log4j-core/org/apache/logging/log4j/core/impl/DefaultLogEventFactory[DefaultLogEventFactory] (GC-free mode: link:../javadoc/log4j-core/org/apache/logging/log4j/core/impl/ReusableLogEventFactory[ReusableLogEventFactory])`
|===

Specifies the link:../javadoc/log4j-core/org/apache/logging/log4j/core/impl/LogEventFactory[LogEventFactory] implementation to use to create log events.

[[log4j2.shutdownHookEnabled]]
== `log4j2.shutdownHookEnabled`

[cols="1h,5"]
|===
| Env. variable | LOG4J_SHUTDOWN_HOOK_ENABLED
| Default value | `true` (Web-app mode: `false`)
|===

If `true` a shutdown hook will be installed to stop all logger contexts when the system stops.

[[log4j2.shutdownCallbackRegistry]]
== `log4j2.shutdownCallbackRegistry`

[cols="1h,5"]
|===
| Env. variable | LOG4J_SHUTDOWN_CALLBACK_REGISTRY
| Default value | `link:../javadoc/log4j-core/org/apache/logging/log4j/core/util/DefaultShutdownCallbackRegistry[DefaultShutdownCallbackRegistry]`
|===

The fully qualified class name of a link:../javadoc/log4j-core/org/apache/logging/log4j/core/util/ShutdownCallbackRegistry[ShutdownCallbackRegistry] implementation.
Integrators can use this to customize the shutdown order of the JVM.

The default implementation executes all shutdown actions in a separate `Thread` registered through https://docs.oracle.com/javase/8/docs/api/java/lang/Runtime.html#addShutdownHook-java.lang.Thread-[Runtime#addShutdownHook()].

[[log4j2.uuidSequence]]
== `log4j2.uuidSequence`

[cols="1h,5"]
|===
| Env. variable | LOG4J_UUID_SEQUENCE
| Default value | `0`
|===

Provides a `long` see to the UUID generator used by the `%uuid` pattern converter.

Can be used to assure uniqueness of UUIDs generated by multiple JVMs on the same machine.

[[log4j2.messageFactory]]
== `log4j2.messageFactory`

[cols="1h,5"]
|===
| Env. variable | LOG4J_MESSAGE_FACTORY
| Default value | link:../javadoc/log4j-api/org/apache/logging/log4j/message/ParameterizedMessageFactory[ParameterizeMessageFactory] (GC-free mode: link:../javadoc/log4j-api/org/apache/logging/log4j/message/ReusableMessageFactory[ReusableMessageFactory])
|===

Default message factory used by loggers if no factory was specified.

[[log4j2.flowMessageFactory]]
== `log4j2.flowMessageFactory`

[cols="1h,5"]
|===
| Env. variable | LOG4J_FLOW_MESSAGE_FACTORY
| Default value | `link:../javadoc/log4j-api/org/apache/logging/log4j/message/DefaultFlowMessageFactory[DefaultFlowMessageFactory]`
|===

Default flow message factory used by Loggers.

[[log4j2.loggerContextStacktraceOnStart]]
== `log4j2.loggerContextStacktraceOnStart`

[cols="1h,5"]
|===
| Env. variable | LOG4J_LOGGER_CONTEXT_STACKTRACE_ON_START
| Default value | ``false``
|===

Prints a stacktrace to the xref:manual/configuration.adoc#StatusMessages[status logger] at `DEBUG` level when the LoggerContext is started.

For debug purposes only.

[[log4j2.scriptEnableLanguages]]
== `log4j2.scriptEnableLanguages`

[cols="1h,5"]
|===
| Env. variable | LOG4J_SCRIPT_ENABLE_LANGUAGES
| Default value | _empty_
|===

The list of script languages that are allowed to execute.

The names specified must correspond to those returned by https://docs.oracle.com/javase/{java-target-version}/docs/api/javax/script/ScriptEngineFactory.html#getNames--[ScriptEngineFactory.getNames()].