#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to you under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: deploy-atr

on:
  push:
    branches:
      - "release-atr/*"

permissions: { }

jobs:

  deploy-atr:
    if: github.repository == 'apache/logging-log4j2'
    runs-on: ubuntu-latest
    permissions:
      id-token: write    # Required for OIDC authentication against ATR
      contents: read
    steps:

      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10    # v6.0.3
        with:
          persist-credentials: false

      - name: Extract version
        id: version
        run: echo "version=${GITHUB_REF_NAME#release-atr/}" >> "$GITHUB_OUTPUT"

      - name: Verify version
        run: |
          version='${{ steps.version.outputs.version }}'
          if ! grep -qF "<revision>${version}</revision>" pom.xml; then
            echo "::error::Mismatch between branch name and project version"
            exit 1
          fi

      - name: Create source distributions
        run: |
          version='${{ steps.version.outputs.version }}'
          prefix="apache-log4j-${version}-src/"
          mkdir -p dist
          git archive --format=tar.gz --prefix="${prefix}" -o "dist/apache-log4j-${version}-src.tar.gz" HEAD
          git archive --format=zip --prefix="${prefix}" -o "dist/apache-log4j-${version}-src.zip" HEAD

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@2dc316deee8e90f13e1a351ab510b4d5bc0c82cd    # v7.0.0
        with:
          gpg_private_key: ${{ secrets.LOGGING_GPG_SECRET_KEY }}

      - name: Generate checksums and signatures
        working-directory: dist
        run: |
          for file in *.tar.gz *.zip; do
            sha256sum "${file}" > "${file}.sha256"
            sha512sum "${file}" > "${file}.sha512"
            gpg --batch --yes --armor --detach-sign --output "${file}.asc" "${file}"
          done

      - name: Upload to ATR
        uses: apache/tooling-actions/upload-to-atr@5bd24e53798bc79aa7bb69f62154a6b1e18ffd6e
        with:
          project: logging-log4j
          version: ${{ steps.version.outputs.version }}
          src: dist
